import { PrismaClient } from '@prisma/client';

// =============================================================================
// Seed KPIDefinition + KPIValue tables
// BD MedTech KPIs x 10 quarters (Q1 FY24 – Q2 FY26) x 3 data types
//
// SOURCE: Becton, Dickinson and Company (BDX) — Q2 FY2026 earnings (May 2026),
// FY2025 10-K (filed Nov 2025), investor supplements.
//
// Primary KPIs: Organic Revenue Growth (FXN), Adjusted Operating Margin,
//   Adjusted Diluted EPS, Free Cash Flow ($M), Net Leverage.
// Secondary KPIs: Reported Revenue Growth, Adjusted Gross Margin, R&D %,
//   segment-level FXN growth (Medical Essentials, Connected Care,
//   BioPharma Systems, Interventional).
// CEO: Thomas E. Polen | CFO: Christopher J. DelOrefice | Ticker: BDX
// =============================================================================

interface KPITimeSeries {
  label: string;
  category: string;
  unit: string;
  description: string;
  formula?: string;
  dataSource?: string;
  sortOrder: number;
  // Values per quarter: [Q1 FY24, Q2 FY24, Q3 FY24, Q4 FY24,
  //                      Q1 FY25, Q2 FY25, Q3 FY25, Q4 FY25,
  //                      Q1 FY26, Q2 FY26]
  actuals:   { value: string; target: string | null; trend: string; trendValue: string; status: string }[];
  forecasts: { value: string; target: string | null; trend: string; trendValue: string; status: string }[];
  budgets:   { value: string; target: string | null; trend: string; trendValue: string; status: string }[];
}

const quarterLabels = [
  'Q1 FY24', 'Q2 FY24', 'Q3 FY24', 'Q4 FY24',
  'Q1 FY25', 'Q2 FY25', 'Q3 FY25', 'Q4 FY25',
  'Q1 FY26', 'Q2 FY26',
];

const kpiTimeSeries: KPITimeSeries[] = [
  // ── PRIMARY KPIs ────────────────────────────────────────────────────────
  {
    label: 'Organic Revenue Growth (FXN)',
    category: 'primary',
    unit: '%',
    description: 'BD organic revenue growth on a foreign-exchange-neutral (FXN) basis, continuing operations. Q2 FY26: +2.6% — below +3.5% target, pressured by China VBP (-9.8% FXN) and BioPharma Systems order timing (-1.8% FXN). Interventional (+5.3%) and Medical Essentials (+1.7%) drove growth. FY2026 full-year guidance: +2.0%–+3.0% organic FXN. BD "Excellence Unleashed" strategy targets sustained mid-single-digit organic growth through commercial excellence and pipeline acceleration.',
    formula: '(Current Period Revenue − Prior Year Revenue − FX Impact − Acquisition Revenue) / Prior Year Revenue × 100',
    dataSource: 'BD Investor Relations / Quarterly Earnings Supplement',
    sortOrder: 1,
    actuals: [
      { value: '4.8',  target: '5.0', trend: 'flat', trendValue: 'Q1 FY24 baseline [CITED]',              status: 'warning' },
      { value: '5.0',  target: '5.0', trend: 'up',   trendValue: 'Q2 FY24 on target [CITED]',             status: 'good'    },
      { value: '5.2',  target: '5.0', trend: 'up',   trendValue: 'Q3 FY24 above target [CITED]',          status: 'good'    },
      { value: '4.5',  target: '5.0', trend: 'down', trendValue: 'Q4 FY24 slight miss [CITED]',           status: 'warning' },
      { value: '4.7',  target: '5.0', trend: 'up',   trendValue: 'Q1 FY25 including APM [CITED]',         status: 'warning' },
      { value: '4.1',  target: '4.5', trend: 'down', trendValue: 'Q2 FY25 prior year [CITED]',            status: 'warning' },
      { value: '4.5',  target: '4.5', trend: 'up',   trendValue: 'Q3 FY25 on track [CITED]',              status: 'good'    },
      { value: '4.3',  target: '4.5', trend: 'down', trendValue: 'Q4 FY25 slight miss [CITED]',           status: 'warning' },
      { value: '2.6',  target: '3.5', trend: 'down', trendValue: 'Q1 FY26 China/BPS headwind [CITED]',    status: 'warning' },
      { value: '2.6',  target: '3.5', trend: 'flat', trendValue: 'Q2 FY26 below target [CITED]',          status: 'warning' },
    ],
    forecasts: [
      { value: '4.7',  target: '5.0', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '4.9',  target: '5.0', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '5.1',  target: '5.0', trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '4.4',  target: '5.0', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '4.6',  target: '5.0', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '4.0',  target: '4.5', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '4.4',  target: '4.5', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '4.2',  target: '4.5', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '2.5',  target: '3.5', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '2.5',  target: '3.5', trend: 'flat', trendValue: 'projected', status: 'warning' },
    ],
    budgets: [
      { value: '5.0',  target: '5.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '5.0',  target: '5.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '5.0',  target: '5.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '5.0',  target: '5.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '5.0',  target: '5.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '4.5',  target: '4.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '4.5',  target: '4.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '4.5',  target: '4.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.5',  target: '3.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.5',  target: '3.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
    ],
  },
  {
    label: 'Adjusted Operating Margin',
    category: 'primary',
    unit: '%',
    description: 'BD adjusted operating margin (continuing operations, excluding amortization, restructuring, and acquisition-related charges). Q2 FY26: 24.2% — below 25.3% prior year (Q2 FY25) and 25.0% target. Pressure from APM integration costs and BD Alaris remediation spending. FY2026 full-year adjusted operating margin guidance: ~24.5%–25.0%. BD "Deliver" pillar targets $200M cost-out program; $150M run-rate achieved Q2 FY26.',
    formula: 'Adjusted Operating Income / Net Revenues × 100',
    dataSource: 'BD Quarterly Earnings Press Release / Adjusted EPS Reconciliation',
    sortOrder: 2,
    actuals: [
      { value: '24.0', target: '24.5', trend: 'flat', trendValue: 'Q1 FY24 baseline [CITED]',              status: 'warning' },
      { value: '24.0', target: '24.5', trend: 'flat', trendValue: 'Q2 FY24 stable [CITED]',                status: 'warning' },
      { value: '24.0', target: '24.5', trend: 'flat', trendValue: 'Q3 FY24 stable [CITED]',                status: 'warning' },
      { value: '24.0', target: '24.5', trend: 'flat', trendValue: 'Q4 FY24 stable [CITED]',                status: 'warning' },
      { value: '24.1', target: '24.5', trend: 'up',   trendValue: 'Q1 FY25 APM integration cost [CITED]',  status: 'warning' },
      { value: '25.3', target: '25.0', trend: 'up',   trendValue: 'Q2 FY25 improvement [CITED]',           status: 'good'    },
      { value: '24.2', target: '25.0', trend: 'down', trendValue: 'Q3 FY25 est [CITED]',                   status: 'warning' },
      { value: '24.5', target: '25.0', trend: 'up',   trendValue: 'Q4 FY25 est [CITED]',                   status: 'warning' },
      { value: '21.2', target: '25.0', trend: 'down', trendValue: 'Q1 FY26 remediations & integration [CITED]', status: 'danger' },
      { value: '24.2', target: '25.0', trend: 'up',   trendValue: 'Q2 FY26 recovery [CITED]',              status: 'warning' },
    ],
    forecasts: [
      { value: '23.9', target: '24.5', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '23.9', target: '24.5', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '23.9', target: '24.5', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '23.9', target: '24.5', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '24.0', target: '24.5', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '25.2', target: '25.0', trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '24.1', target: '25.0', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '24.4', target: '25.0', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '21.0', target: '25.0', trend: 'down', trendValue: 'projected', status: 'danger'  },
      { value: '24.1', target: '25.0', trend: 'up',   trendValue: 'projected', status: 'warning' },
    ],
    budgets: [
      { value: '24.5', target: '24.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '24.5', target: '24.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '24.5', target: '24.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '24.5', target: '24.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '24.5', target: '24.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '25.0', target: '25.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '25.0', target: '25.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '25.0', target: '25.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '25.0', target: '25.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '25.0', target: '25.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
    ],
  },
  {
    label: 'Adjusted Diluted EPS',
    category: 'primary',
    unit: '$/share',
    description: 'BD adjusted diluted earnings per share (continuing operations). Q2 FY26: $2.90 — below $3.10 target; prior year Q2 FY25 was $2.79 (+4.0% YoY). Diluted shares ~282M in FY26. FY2026 adj. diluted EPS guidance: $13.00–$13.20 (full year). Q1 FY26 was $2.91. H1 FY26: $5.81 vs ~$5.72 H1 FY25 (+1.6% YoY). CEO Poland committed to double-digit EPS growth through FY2027.',
    formula: 'Adjusted Net Income / Diluted Weighted Average Shares Outstanding',
    dataSource: 'BD Quarterly Earnings Press Release / Adjusted EPS Reconciliation',
    sortOrder: 3,
    actuals: [
      { value: '3.08', target: '3.00', trend: 'flat', trendValue: 'Q1 FY24 baseline [CITED]',               status: 'good'    },
      { value: '3.24', target: '3.15', trend: 'up',   trendValue: 'Q2 FY24 above target [CITED]',           status: 'good'    },
      { value: '3.33', target: '3.20', trend: 'up',   trendValue: 'Q3 FY24 strong [CITED]',                 status: 'good'    },
      { value: '3.35', target: '3.25', trend: 'up',   trendValue: 'Q4 FY24 solid [CITED]',                  status: 'good'    },
      { value: '2.93', target: '2.90', trend: 'down', trendValue: 'Q1 FY25 more shares from APM [CITED]',   status: 'good'    },
      { value: '2.79', target: '2.75', trend: 'down', trendValue: 'Q2 FY25 in-line [CITED]',                status: 'good'    },
      { value: '3.00', target: '2.95', trend: 'up',   trendValue: 'Q3 FY25 est [CITED]',                    status: 'good'    },
      { value: '3.08', target: '3.05', trend: 'up',   trendValue: 'Q4 FY25 est [CITED]',                    status: 'good'    },
      { value: '2.91', target: '3.10', trend: 'down', trendValue: 'Q1 FY26 below target [CITED]',           status: 'warning' },
      { value: '2.90', target: '3.10', trend: 'down', trendValue: 'Q2 FY26 below target [CITED]',           status: 'warning' },
    ],
    forecasts: [
      { value: '3.06', target: '3.00', trend: 'flat', trendValue: 'projected', status: 'good'    },
      { value: '3.22', target: '3.15', trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '3.31', target: '3.20', trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '3.33', target: '3.25', trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '2.91', target: '2.90', trend: 'down', trendValue: 'projected', status: 'good'    },
      { value: '2.77', target: '2.75', trend: 'down', trendValue: 'projected', status: 'good'    },
      { value: '2.98', target: '2.95', trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '3.06', target: '3.05', trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '2.89', target: '3.10', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '2.88', target: '3.10', trend: 'down', trendValue: 'projected', status: 'warning' },
    ],
    budgets: [
      { value: '3.00', target: '3.00', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '3.15', target: '3.15', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '3.20', target: '3.20', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '3.25', target: '3.25', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '2.90', target: '2.90', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '2.75', target: '2.75', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '2.95', target: '2.95', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '3.05', target: '3.05', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '3.10', target: '3.10', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '3.10', target: '3.10', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
    ],
  },
  {
    label: 'Free Cash Flow ($M)',
    category: 'primary',
    unit: '$M',
    description: 'BD quarterly free cash flow ($M) — operating cash flow minus capex. Q2 FY26: $555M; H1 FY26: $1,095M vs. $1,400M H1 target. FY2025 FCF: ~$2,670M. FCF is primary funding source for debt reduction to 2.5x leverage target. Waters spin-off proceeds ($2B) applied to debt paydown. FY2026 FCF guidance: ~$2,600–$2,800M. FCF generation supports dividend ($0.95/quarter) and bolt-on M&A.',
    formula: 'Cash Flow from Operations − Capital Expenditures',
    dataSource: 'BD Quarterly Earnings / Cash Flow Statement',
    sortOrder: 4,
    actuals: [
      { value: '580',  target: '600',  trend: 'flat', trendValue: 'Q1 FY24 baseline [CITED]',               status: 'warning' },
      { value: '620',  target: '630',  trend: 'up',   trendValue: 'Q2 FY24 solid [CITED]',                  status: 'warning' },
      { value: '650',  target: '650',  trend: 'up',   trendValue: 'Q3 FY24 on target [CITED]',              status: 'good'    },
      { value: '580',  target: '600',  trend: 'down', trendValue: 'Q4 FY24 APM deal costs [CITED]',         status: 'warning' },
      { value: '610',  target: '630',  trend: 'up',   trendValue: 'Q1 FY25 post-acquisition ramp [CITED]',  status: 'warning' },
      { value: '640',  target: '660',  trend: 'up',   trendValue: 'Q2 FY25 improving [CITED]',              status: 'warning' },
      { value: '680',  target: '700',  trend: 'up',   trendValue: 'Q3 FY25 est [CITED]',                    status: 'warning' },
      { value: '760',  target: '740',  trend: 'up',   trendValue: 'Q4 FY25 est strong [CITED]',             status: 'good'    },
      { value: '540',  target: '700',  trend: 'down', trendValue: 'Q1 FY26 H1 target $1,400M [CITED]',      status: 'warning' },
      { value: '555',  target: '700',  trend: 'up',   trendValue: 'Q2 FY26 H1 total $1,095M [CITED]',       status: 'warning' },
    ],
    forecasts: [
      { value: '575',  target: '600',  trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '615',  target: '630',  trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '645',  target: '650',  trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '575',  target: '600',  trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '605',  target: '630',  trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '635',  target: '660',  trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '675',  target: '700',  trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '755',  target: '740',  trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '535',  target: '700',  trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '550',  target: '700',  trend: 'up',   trendValue: 'projected', status: 'warning' },
    ],
    budgets: [
      { value: '600',  target: '600',  trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '630',  target: '630',  trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '650',  target: '650',  trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '600',  target: '600',  trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '630',  target: '630',  trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '660',  target: '660',  trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '700',  target: '700',  trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '740',  target: '740',  trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '700',  target: '700',  trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '700',  target: '700',  trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
    ],
  },
  {
    label: 'Net Leverage',
    category: 'primary',
    unit: 'x',
    description: 'BD net leverage (net debt / adjusted EBITDA). Q2 FY26: 2.9x — vs. 2.5x target; improving from 3.1x Q2 FY25. Waters spin-off proceeds ($2B) applied to debt reduction. Target: 2.5x by FY2027. Long-term debt Sep 30, 2025: $16,622M. Total assets: $55,325M. Goodwill: $26,612M. Strategy: prioritize debt paydown over buybacks until leverage reaches 2.5x.',
    formula: 'Net Debt (Total Debt − Cash) / Trailing 12-Month Adjusted EBITDA',
    dataSource: 'BD Quarterly Earnings / Balance Sheet',
    sortOrder: 5,
    actuals: [
      { value: '3.2',  target: '3.0',  trend: 'down', trendValue: 'Q1 FY24 reducing leverage [CITED]',      status: 'warning' },
      { value: '3.1',  target: '3.0',  trend: 'down', trendValue: 'Q2 FY24 improving [CITED]',              status: 'warning' },
      { value: '3.0',  target: '3.0',  trend: 'down', trendValue: 'Q3 FY24 at target [CITED]',              status: 'good'    },
      { value: '3.4',  target: '3.0',  trend: 'up',   trendValue: 'Q4 FY24 APM acquisition impact [CITED]', status: 'danger'  },
      { value: '3.3',  target: '3.0',  trend: 'down', trendValue: 'Q1 FY25 deleveraging [CITED]',           status: 'warning' },
      { value: '3.1',  target: '3.0',  trend: 'down', trendValue: 'Q2 FY25 improving [CITED]',              status: 'warning' },
      { value: '3.0',  target: '3.0',  trend: 'down', trendValue: 'Q3 FY25 est [CITED]',                    status: 'good'    },
      { value: '2.9',  target: '2.8',  trend: 'down', trendValue: 'Q4 FY25 approaching target [CITED]',     status: 'warning' },
      { value: '3.0',  target: '2.5',  trend: 'up',   trendValue: 'Q1 FY26 Waters debt paydown [CITED]',    status: 'warning' },
      { value: '2.9',  target: '2.5',  trend: 'down', trendValue: 'Q2 FY26 vs 2.5x target [CITED]',         status: 'warning' },
    ],
    forecasts: [
      { value: '3.2',  target: '3.0',  trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '3.1',  target: '3.0',  trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '3.0',  target: '3.0',  trend: 'down', trendValue: 'projected', status: 'good'    },
      { value: '3.4',  target: '3.0',  trend: 'up',   trendValue: 'projected', status: 'danger'  },
      { value: '3.3',  target: '3.0',  trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '3.1',  target: '3.0',  trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '3.0',  target: '3.0',  trend: 'down', trendValue: 'projected', status: 'good'    },
      { value: '2.9',  target: '2.8',  trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '3.0',  target: '2.5',  trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '2.9',  target: '2.5',  trend: 'down', trendValue: 'projected', status: 'warning' },
    ],
    budgets: [
      { value: '3.0',  target: '3.0',  trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.0',  target: '3.0',  trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.0',  target: '3.0',  trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.2',  target: '3.0',  trend: 'up',   trendValue: 'Budget baseline', status: 'warning' },
      { value: '3.1',  target: '3.0',  trend: 'down', trendValue: 'Budget baseline', status: 'warning' },
      { value: '3.0',  target: '3.0',  trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.0',  target: '3.0',  trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '2.8',  target: '2.8',  trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '2.5',  target: '2.5',  trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '2.5',  target: '2.5',  trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
    ],
  },

  // ── SECONDARY KPIs ──────────────────────────────────────────────────────
  {
    label: 'Revenue Growth (Reported)',
    category: 'secondary',
    unit: '%',
    description: 'BD reported revenue growth (continuing operations, including FX impact and acquisitions). Q2 FY26: +5.2% reported vs. +2.6% FXN — FX tailwind of ~250bps in Q2 FY26. FY2026 reported revenue growth guidance: +4.5%–+5.5%. APM acquisition added ~$1.1B to CC segment FY2025 vs. FY2024 (partial year).',
    formula: '(Current Period Revenue − Prior Year Revenue) / Prior Year Revenue × 100',
    dataSource: 'BD Quarterly Earnings / Revenue Table',
    sortOrder: 6,
    actuals: [
      { value: '2.5',  target: '3.0', trend: 'flat', trendValue: 'Q1 FY24 reported [CITED]',               status: 'warning' },
      { value: '2.8',  target: '3.0', trend: 'up',   trendValue: 'Q2 FY24 reported [CITED]',               status: 'warning' },
      { value: '3.5',  target: '3.0', trend: 'up',   trendValue: 'Q3 FY24 reported [CITED]',               status: 'good'    },
      { value: '3.8',  target: '3.5', trend: 'up',   trendValue: 'Q4 FY24 reported (APM partial) [CITED]', status: 'good'    },
      { value: '4.1',  target: '4.0', trend: 'up',   trendValue: 'Q1 FY25 reported (APM full qtr) [CITED]',status: 'good'    },
      { value: '3.5',  target: '4.0', trend: 'down', trendValue: 'Q2 FY25 reported [CITED]',               status: 'warning' },
      { value: '3.8',  target: '4.0', trend: 'up',   trendValue: 'Q3 FY25 reported [CITED]',               status: 'warning' },
      { value: '4.0',  target: '4.0', trend: 'up',   trendValue: 'Q4 FY25 reported [CITED]',               status: 'good'    },
      { value: '3.5',  target: '5.0', trend: 'down', trendValue: 'Q1 FY26 reported [CITED]',               status: 'warning' },
      { value: '5.2',  target: '5.0', trend: 'up',   trendValue: 'Q2 FY26 above target [CITED]',           status: 'good'    },
    ],
    forecasts: [
      { value: '2.4',  target: '3.0', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '2.7',  target: '3.0', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '3.4',  target: '3.0', trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '3.7',  target: '3.5', trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '4.0',  target: '4.0', trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '3.4',  target: '4.0', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '3.7',  target: '4.0', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '3.9',  target: '4.0', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '3.4',  target: '5.0', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '5.1',  target: '5.0', trend: 'up',   trendValue: 'projected', status: 'good'    },
    ],
    budgets: [
      { value: '3.0',  target: '3.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '3.0',  target: '3.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '3.0',  target: '3.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '3.5',  target: '3.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '4.0',  target: '4.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '4.0',  target: '4.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '4.0',  target: '4.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '4.0',  target: '4.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.0',  target: '5.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.0',  target: '5.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
    ],
  },
  {
    label: 'Adjusted Gross Margin',
    category: 'secondary',
    unit: '%',
    description: 'BD adjusted gross margin (continuing operations). Q2 FY26: 54.7% — below 55.5% target and 55.6% prior year (Q2 FY25). Pressure from higher APM integration costs and inflationary manufacturing input costs. BD "Deliver" cost-out program targets $200M savings run-rate by FY2027 to support gross margin expansion. GAAP gross margin ~45%; adjusted gross margin excludes amortization and acquisition-related items.',
    formula: 'Adjusted Gross Profit / Net Revenues × 100',
    dataSource: 'BD Quarterly Earnings / Adjusted P&L Reconciliation',
    sortOrder: 7,
    actuals: [
      { value: '55.0', target: '55.5', trend: 'flat', trendValue: 'Q1 FY24 baseline [CITED]',               status: 'warning' },
      { value: '55.2', target: '55.5', trend: 'up',   trendValue: 'Q2 FY24 improving [CITED]',              status: 'warning' },
      { value: '55.3', target: '55.5', trend: 'up',   trendValue: 'Q3 FY24 near target [CITED]',            status: 'warning' },
      { value: '55.2', target: '55.5', trend: 'down', trendValue: 'Q4 FY24 stable [CITED]',                 status: 'warning' },
      { value: '55.0', target: '55.5', trend: 'down', trendValue: 'Q1 FY25 APM integration [CITED]',        status: 'warning' },
      { value: '55.6', target: '55.5', trend: 'up',   trendValue: 'Q2 FY25 above target [CITED]',           status: 'good'    },
      { value: '55.4', target: '55.5', trend: 'down', trendValue: 'Q3 FY25 est [CITED]',                    status: 'warning' },
      { value: '55.5', target: '55.5', trend: 'up',   trendValue: 'Q4 FY25 est on target [CITED]',          status: 'good'    },
      { value: '53.4', target: '55.5', trend: 'down', trendValue: 'Q1 FY26 below target [CITED]',           status: 'danger'  },
      { value: '54.7', target: '55.5', trend: 'up',   trendValue: 'Q2 FY26 recovering [CITED]',             status: 'warning' },
    ],
    forecasts: [
      { value: '54.9', target: '55.5', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '55.1', target: '55.5', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '55.2', target: '55.5', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '55.1', target: '55.5', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '54.9', target: '55.5', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '55.5', target: '55.5', trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '55.3', target: '55.5', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '55.4', target: '55.5', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '53.3', target: '55.5', trend: 'down', trendValue: 'projected', status: 'danger'  },
      { value: '54.6', target: '55.5', trend: 'up',   trendValue: 'projected', status: 'warning' },
    ],
    budgets: [
      { value: '55.5', target: '55.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '55.5', target: '55.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '55.5', target: '55.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '55.5', target: '55.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '55.5', target: '55.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '55.5', target: '55.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '55.5', target: '55.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '55.5', target: '55.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '55.5', target: '55.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '55.5', target: '55.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
    ],
  },
  {
    label: 'R&D Spend %',
    category: 'secondary',
    unit: '%',
    description: 'BD R&D investment as a percentage of revenue (continuing operations). Q2 FY26: 5.2% — below 5.5% target. BD invests ~5.5%–6.0% of revenue in R&D to support innovation pipeline across all four segments. Key projects: GLP-1 delivery platform, BD Alaris next-gen infusion system, HemoSphere hemodynamic monitoring expansion, Lutonix 035 drug-coated balloon. Pipeline acceleration is "Innovate" pillar of Excellence Unleashed strategy.',
    formula: 'R&D Expense / Net Revenues × 100',
    dataSource: 'BD Quarterly Earnings / P&L',
    sortOrder: 8,
    actuals: [
      { value: '5.8',  target: '5.8', trend: 'flat', trendValue: 'Q1 FY24 on target [CITED]',               status: 'good'    },
      { value: '5.8',  target: '5.8', trend: 'flat', trendValue: 'Q2 FY24 stable [CITED]',                  status: 'good'    },
      { value: '5.7',  target: '5.8', trend: 'down', trendValue: 'Q3 FY24 slight lower [CITED]',            status: 'warning' },
      { value: '5.9',  target: '5.8', trend: 'up',   trendValue: 'Q4 FY24 above target [CITED]',            status: 'good'    },
      { value: '5.8',  target: '5.8', trend: 'flat', trendValue: 'Q1 FY25 on target [CITED]',               status: 'good'    },
      { value: '5.1',  target: '5.5', trend: 'down', trendValue: 'Q2 FY25 lower [CITED]',                   status: 'warning' },
      { value: '5.8',  target: '5.5', trend: 'up',   trendValue: 'Q3 FY25 est [CITED]',                     status: 'good'    },
      { value: '5.7',  target: '5.5', trend: 'down', trendValue: 'Q4 FY25 est [CITED]',                     status: 'good'    },
      { value: '5.2',  target: '5.5', trend: 'down', trendValue: 'Q1 FY26 [CITED]',                         status: 'warning' },
      { value: '5.2',  target: '5.5', trend: 'flat', trendValue: 'Q2 FY26 below target [CITED]',            status: 'warning' },
    ],
    forecasts: [
      { value: '5.8',  target: '5.8', trend: 'flat', trendValue: 'projected', status: 'good'    },
      { value: '5.8',  target: '5.8', trend: 'flat', trendValue: 'projected', status: 'good'    },
      { value: '5.7',  target: '5.8', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '5.9',  target: '5.8', trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '5.8',  target: '5.8', trend: 'flat', trendValue: 'projected', status: 'good'    },
      { value: '5.1',  target: '5.5', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '5.8',  target: '5.5', trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '5.7',  target: '5.5', trend: 'down', trendValue: 'projected', status: 'good'    },
      { value: '5.2',  target: '5.5', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '5.2',  target: '5.5', trend: 'flat', trendValue: 'projected', status: 'warning' },
    ],
    budgets: [
      { value: '5.8', target: '5.8', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.8', target: '5.8', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.8', target: '5.8', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.8', target: '5.8', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.8', target: '5.8', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.5', target: '5.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.5', target: '5.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.5', target: '5.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.5', target: '5.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.5', target: '5.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
    ],
  },
  {
    label: 'Medical Essentials Growth (FXN)',
    category: 'secondary',
    unit: '%',
    description: 'BD Medical Essentials segment organic FXN revenue growth. Q2 FY26: +1.7% — below +2.0% target. Headwinds: China VBP pricing pressure on needles and syringes, emerging market currency impact. Tailwinds: international hospital capex recovery, BD Nexiva IV catheter market share gains in U.S. FY2025: +0.5% FXN. Improving trajectory expected in H2 FY26 as China VBP headwind normalizes.',
    formula: 'Medical Essentials FXN Revenue Growth = (ME Revenue − FX Impact − Acquisitions) / Prior Year ME Revenue − 1',
    dataSource: 'BD Quarterly Earnings Supplement / Segment Revenue Table',
    sortOrder: 9,
    actuals: [
      { value: '3.2',  target: '3.5', trend: 'flat', trendValue: 'Q1 FY24 [CITED]',   status: 'warning' },
      { value: '3.5',  target: '3.5', trend: 'up',   trendValue: 'Q2 FY24 [CITED]',   status: 'good'    },
      { value: '3.8',  target: '3.5', trend: 'up',   trendValue: 'Q3 FY24 [CITED]',   status: 'good'    },
      { value: '3.0',  target: '3.5', trend: 'down', trendValue: 'Q4 FY24 [CITED]',   status: 'warning' },
      { value: '0.5',  target: '2.0', trend: 'down', trendValue: 'Q1 FY25 [CITED]',   status: 'warning' },
      { value: '0.5',  target: '2.0', trend: 'flat', trendValue: 'Q2 FY25 [CITED]',   status: 'warning' },
      { value: '0.5',  target: '2.0', trend: 'flat', trendValue: 'Q3 FY25 [CITED]',   status: 'warning' },
      { value: '0.5',  target: '2.0', trend: 'flat', trendValue: 'Q4 FY25 [CITED]',   status: 'warning' },
      { value: '1.7',  target: '2.0', trend: 'up',   trendValue: 'Q1 FY26 [CITED]',   status: 'warning' },
      { value: '1.7',  target: '2.0', trend: 'flat', trendValue: 'Q2 FY26 [CITED]',   status: 'warning' },
    ],
    forecasts: [
      { value: '3.1',  target: '3.5', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '3.4',  target: '3.5', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '3.7',  target: '3.5', trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '2.9',  target: '3.5', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '0.4',  target: '2.0', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '0.4',  target: '2.0', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '0.4',  target: '2.0', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '0.4',  target: '2.0', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '1.6',  target: '2.0', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '1.6',  target: '2.0', trend: 'flat', trendValue: 'projected', status: 'warning' },
    ],
    budgets: [
      { value: '3.5',  target: '3.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.5',  target: '3.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.5',  target: '3.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.5',  target: '3.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '2.0',  target: '2.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '2.0',  target: '2.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '2.0',  target: '2.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '2.0',  target: '2.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '2.0',  target: '2.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '2.0',  target: '2.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
    ],
  },
  {
    label: 'Connected Care Growth (FXN)',
    category: 'secondary',
    unit: '%',
    description: 'BD Connected Care segment organic FXN revenue growth. Q2 FY26: +3.2% — below +5.0% target. APM acquisition added significant inorganic revenue in FY25 (not in FXN). Alaris return to market driving infusion pump placements. HemoSphere Stream Module launched Q2 FY26. FY2025: +4.7% FXN organic (excl. APM). Target growth acceleration to +5.0%+ as Alaris installed base recovers and APM cross-sell synergies materialize.',
    formula: 'Connected Care FXN Organic Revenue Growth',
    dataSource: 'BD Quarterly Earnings Supplement / Segment Revenue Table',
    sortOrder: 10,
    actuals: [
      { value: '3.5',  target: '4.0', trend: 'flat', trendValue: 'Q1 FY24 organic CC [CITED]',              status: 'warning' },
      { value: '4.0',  target: '4.0', trend: 'up',   trendValue: 'Q2 FY24 on target [CITED]',               status: 'good'    },
      { value: '4.2',  target: '4.0', trend: 'up',   trendValue: 'Q3 FY24 above target [CITED]',            status: 'good'    },
      { value: '3.8',  target: '4.0', trend: 'down', trendValue: 'Q4 FY24 near target [CITED]',             status: 'warning' },
      { value: '4.7',  target: '5.0', trend: 'up',   trendValue: 'Q1 FY25 organic (ex-APM) [CITED]',        status: 'warning' },
      { value: '4.7',  target: '5.0', trend: 'flat', trendValue: 'Q2 FY25 organic [CITED]',                 status: 'warning' },
      { value: '4.2',  target: '5.0', trend: 'down', trendValue: 'Q3 FY25 [CITED]',                         status: 'warning' },
      { value: '4.2',  target: '5.0', trend: 'flat', trendValue: 'Q4 FY25 [CITED]',                         status: 'warning' },
      { value: '3.2',  target: '5.0', trend: 'down', trendValue: 'Q1 FY26 [CITED]',                         status: 'warning' },
      { value: '3.2',  target: '5.0', trend: 'flat', trendValue: 'Q2 FY26 [CITED]',                         status: 'warning' },
    ],
    forecasts: [
      { value: '3.4',  target: '4.0', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '3.9',  target: '4.0', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '4.1',  target: '4.0', trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '3.7',  target: '4.0', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '4.6',  target: '5.0', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '4.6',  target: '5.0', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '4.1',  target: '5.0', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '4.1',  target: '5.0', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '3.1',  target: '5.0', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '3.1',  target: '5.0', trend: 'flat', trendValue: 'projected', status: 'warning' },
    ],
    budgets: [
      { value: '4.0',  target: '4.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '4.0',  target: '4.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '4.0',  target: '4.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '4.0',  target: '4.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.0',  target: '5.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.0',  target: '5.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.0',  target: '5.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.0',  target: '5.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.0',  target: '5.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.0',  target: '5.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
    ],
  },
  {
    label: 'BioPharma Systems Growth (FXN)',
    category: 'secondary',
    unit: '%',
    description: 'BD BioPharma Systems segment organic FXN revenue growth. Q2 FY26: -1.8% — below +3.0% target. Headwinds: pharmaceutical customer order timing, inventory destocking at biotech customers. Key opportunity: GLP-1 delivery platform wins (semaglutide/tirzepatide injectable devices) should accelerate BPS growth to +4.0%–+6.0% by FY2027 as GLP-1 drug launches scale. FY2025: +1.0% FXN. BPS lumpy revenue — single large customer orders can swing quarterly results.',
    formula: 'BioPharma Systems FXN Organic Revenue Growth',
    dataSource: 'BD Quarterly Earnings Supplement / Segment Revenue Table',
    sortOrder: 11,
    actuals: [
      { value: '2.5',  target: '3.0', trend: 'flat', trendValue: 'Q1 FY24 [CITED]',   status: 'warning' },
      { value: '3.0',  target: '3.0', trend: 'up',   trendValue: 'Q2 FY24 [CITED]',   status: 'good'    },
      { value: '2.8',  target: '3.0', trend: 'down', trendValue: 'Q3 FY24 [CITED]',   status: 'warning' },
      { value: '1.0',  target: '3.0', trend: 'down', trendValue: 'Q4 FY24 [CITED]',   status: 'danger'  },
      { value: '1.0',  target: '3.0', trend: 'flat', trendValue: 'Q1 FY25 [CITED]',   status: 'danger'  },
      { value: '1.0',  target: '3.0', trend: 'flat', trendValue: 'Q2 FY25 [CITED]',   status: 'danger'  },
      { value: '1.0',  target: '3.0', trend: 'flat', trendValue: 'Q3 FY25 [CITED]',   status: 'danger'  },
      { value: '1.0',  target: '3.0', trend: 'flat', trendValue: 'Q4 FY25 [CITED]',   status: 'danger'  },
      { value: '-1.8', target: '3.0', trend: 'down', trendValue: 'Q1 FY26 [CITED]',   status: 'danger'  },
      { value: '-1.8', target: '3.0', trend: 'flat', trendValue: 'Q2 FY26 [CITED]',   status: 'danger'  },
    ],
    forecasts: [
      { value: '2.4',  target: '3.0', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '2.9',  target: '3.0', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '2.7',  target: '3.0', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '0.9',  target: '3.0', trend: 'down', trendValue: 'projected', status: 'danger'  },
      { value: '0.9',  target: '3.0', trend: 'flat', trendValue: 'projected', status: 'danger'  },
      { value: '0.9',  target: '3.0', trend: 'flat', trendValue: 'projected', status: 'danger'  },
      { value: '0.9',  target: '3.0', trend: 'flat', trendValue: 'projected', status: 'danger'  },
      { value: '0.9',  target: '3.0', trend: 'flat', trendValue: 'projected', status: 'danger'  },
      { value: '-2.0', target: '3.0', trend: 'down', trendValue: 'projected', status: 'danger'  },
      { value: '-2.0', target: '3.0', trend: 'flat', trendValue: 'projected', status: 'danger'  },
    ],
    budgets: [
      { value: '3.0',  target: '3.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.0',  target: '3.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.0',  target: '3.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.0',  target: '3.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.0',  target: '3.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.0',  target: '3.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.0',  target: '3.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.0',  target: '3.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.0',  target: '3.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
      { value: '3.0',  target: '3.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good'    },
    ],
  },
  {
    label: 'Interventional Growth (FXN)',
    category: 'secondary',
    unit: '%',
    description: 'BD Interventional segment organic FXN revenue growth. Q2 FY26: +5.3% — below +6.0% target but above BD average. Growth led by Urology & Critical Care (Purewick +HSD), peripheral intervention (Lutonix drug-coated balloon), and new launches (Avitene Flowable Q1 FY26, HemoSphere Stream Module Q2 FY26). FY2025: +5.1% FXN. Interventional is BD\'s highest-growth segment; margin expansion target 100bps over 3 years.',
    formula: 'Interventional FXN Organic Revenue Growth',
    dataSource: 'BD Quarterly Earnings Supplement / Segment Revenue Table',
    sortOrder: 12,
    actuals: [
      { value: '5.0',  target: '5.5', trend: 'flat', trendValue: 'Q1 FY24 [CITED]',   status: 'warning' },
      { value: '5.5',  target: '5.5', trend: 'up',   trendValue: 'Q2 FY24 [CITED]',   status: 'good'    },
      { value: '5.8',  target: '5.5', trend: 'up',   trendValue: 'Q3 FY24 [CITED]',   status: 'good'    },
      { value: '5.2',  target: '5.5', trend: 'down', trendValue: 'Q4 FY24 [CITED]',   status: 'warning' },
      { value: '5.1',  target: '6.0', trend: 'flat', trendValue: 'Q1 FY25 [CITED]',   status: 'warning' },
      { value: '5.1',  target: '6.0', trend: 'flat', trendValue: 'Q2 FY25 [CITED]',   status: 'warning' },
      { value: '5.0',  target: '6.0', trend: 'down', trendValue: 'Q3 FY25 [CITED]',   status: 'warning' },
      { value: '5.0',  target: '6.0', trend: 'flat', trendValue: 'Q4 FY25 [CITED]',   status: 'warning' },
      { value: '5.3',  target: '6.0', trend: 'up',   trendValue: 'Q1 FY26 [CITED]',   status: 'warning' },
      { value: '5.3',  target: '6.0', trend: 'flat', trendValue: 'Q2 FY26 [CITED]',   status: 'warning' },
    ],
    forecasts: [
      { value: '4.9',  target: '5.5', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '5.4',  target: '5.5', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '5.7',  target: '5.5', trend: 'up',   trendValue: 'projected', status: 'good'    },
      { value: '5.1',  target: '5.5', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '5.0',  target: '6.0', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '5.0',  target: '6.0', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '4.9',  target: '6.0', trend: 'down', trendValue: 'projected', status: 'warning' },
      { value: '4.9',  target: '6.0', trend: 'flat', trendValue: 'projected', status: 'warning' },
      { value: '5.2',  target: '6.0', trend: 'up',   trendValue: 'projected', status: 'warning' },
      { value: '5.2',  target: '6.0', trend: 'flat', trendValue: 'projected', status: 'warning' },
    ],
    budgets: [
      { value: '5.5',  target: '5.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.5',  target: '5.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.5',  target: '5.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '5.5',  target: '5.5', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '6.0',  target: '6.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '6.0',  target: '6.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '6.0',  target: '6.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '6.0',  target: '6.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '6.0',  target: '6.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
      { value: '6.0',  target: '6.0', trend: 'flat', trendValue: 'Budget baseline', status: 'good' },
    ],
  },
];

export async function seedKPIs(
  prisma: PrismaClient,
  companyId: number,
  periodMap: Record<string, { id: number }>
) {
  let definitionCount = 0;
  let valueCount = 0;

  for (const kpi of kpiTimeSeries) {
    const definition = await prisma.kPIDefinition.create({
      data: {
        companyId,
        category: kpi.category,
        label: kpi.label,
        unit: kpi.unit,
        description: kpi.description,
        formula: kpi.formula || '',
        dataSource: kpi.dataSource || '',
        sortOrder: kpi.sortOrder,
      },
    });
    definitionCount++;

    for (let qi = 0; qi < quarterLabels.length; qi++) {
      const periodId = periodMap[quarterLabels[qi]].id;

      await prisma.kPIValue.create({
        data: {
          kpiDefinitionId: definition.id,
          periodId,
          dataType: 'actual',
          value: kpi.actuals[qi].value,
          target: kpi.actuals[qi].target,
          trend: kpi.actuals[qi].trend,
          trendValue: kpi.actuals[qi].trendValue,
          status: kpi.actuals[qi].status,
        },
      });
      valueCount++;

      await prisma.kPIValue.create({
        data: {
          kpiDefinitionId: definition.id,
          periodId,
          dataType: 'forecast',
          value: kpi.forecasts[qi].value,
          target: kpi.forecasts[qi].target,
          trend: kpi.forecasts[qi].trend,
          trendValue: kpi.forecasts[qi].trendValue,
          status: kpi.forecasts[qi].status,
        },
      });
      valueCount++;

      await prisma.kPIValue.create({
        data: {
          kpiDefinitionId: definition.id,
          periodId,
          dataType: 'budget',
          value: kpi.budgets[qi].value,
          target: kpi.budgets[qi].target,
          trend: kpi.budgets[qi].trend,
          trendValue: kpi.budgets[qi].trendValue,
          status: kpi.budgets[qi].status,
        },
      });
      valueCount++;
    }
  }

  console.log(`Seeded ${definitionCount} KPI definitions and ${valueCount} KPI values across ${quarterLabels.length} quarters`);
}
