import {
    BarChart3,
    Calendar,
    Clock,
    Building2,
    DollarSign,
    Globe,
    Landmark,
    PieChart,
    Scale,
    Target,
    Users,
} from 'lucide-react';

import type { PersonalizedInsight } from './search-types';

// ── Personalized Insights (BD Finance360 / CFO scoreboard aligned) ─────────
// IDs are stable — HomeTileSection + CFOTiles reference these for modal detail.

export const personalizedInsights: PersonalizedInsight[] = [
    {
        id: 1,
        title: 'China VoBP Headwind: $150M FY26 Plan',
        kpi: '$150M',
        kpiLabel: 'FY26 China VoBP revenue headwind (plan)',
        insight: 'China Volume-Based Procurement (VoBP) represents a planned $150M FY26 revenue headwind for BD. VoBP Round 9 expansion risk could extend to additional BD product categories across Medical Essentials and Interventional, with adverse scenario reaching $220–280M. Emerging markets growth partially offsets the China compression.',
        trend: 'down',
        value: '-$0.06 Adj. EPS per $100M',
        priority: 'high',
        icon: Globe,
        bgColor: 'bg-amber-50',
        iconColor: 'text-amber-700',
        valueColor: 'text-red-600',
        action: 'View Details',
        category: 'China & Geopolitical Risk',
        confidenceScore: 88,
        dataSource: 'BD Q2 FY26 Earnings Call + China VoBP Round 9 Announcements',
        lastUpdated: '2 hours ago',
        aiRecommendations: [
            'Model VoBP Round 9 expansion scenarios: base ($150M), bear ($220M), stress ($280M) — each $100M incremental ≈ −$0.06 Adj. EPS',
            'Track BD emerging markets organic growth as VoBP offset — APAC ex-China and LatAm are primary mitigation channels',
            'Monitor China MedTech regulatory pipeline for additional product categories subject to VoBP tender processes',
        ],
        impactedMetrics: [
            { metric: 'FY26 China VoBP headwind (base)', value: '$150M', trend: 'negative' },
            { metric: 'Adverse VoBP scenario', value: '$220–280M', trend: 'negative' },
            { metric: 'EPS sensitivity per $100M VoBP', value: '−$0.06 Adj. EPS', trend: 'negative' },
        ],
        historicalContext: 'China VoBP procurement reforms began in 2018 and have expanded across medical devices. BD has absorbed VoBP headwinds in needles, syringes, and diagnostics — each round creates price compression of 30–70% on tendered products.',
        predictiveInsight: 'If VoBP Round 9 expands to Interventional vascular and surgical products, the cumulative headwind could approach $300M+ by FY27 — partially offset by BD pricing power in markets outside China and portfolio shift to higher-value systems.',
        dataQuality: 'High',
        modelAccuracy: '87%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 2,
        title: 'Medical Essentials: Largest BD Segment',
        kpi: '~38%',
        kpiLabel: 'Medical Essentials share of BD revenue (FY25)',
        insight: 'BD Medical Essentials is the largest segment at ~38% of revenue, providing medication delivery, infection prevention, and pharmaceutical systems. The segment benefits from hospital channel recovery and long-term contracted supply agreements across acute care.',
        trend: 'up',
        value: '~$7.5B annual revenue',
        priority: 'medium',
        icon: Building2,
        bgColor: 'bg-blue-50',
        iconColor: 'text-[#1c519c]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Segment Performance',
        confidenceScore: 90,
        dataSource: 'BD FY25 Annual Report + Segment Disclosures',
        lastUpdated: '4 hours ago',
        aiRecommendations: [
            'Monitor hospital capital spending trends — Medical Essentials volumes are closely correlated with acute care procedure volumes',
            'Track contract renewal pipeline: long-term GPO agreements provide revenue visibility but compress pricing annually',
            'Assess Medical Essentials margin trajectory — segment margin expansion is a BD Simplify program priority',
        ],
        impactedMetrics: [
            { metric: 'Medical Essentials revenue share', value: '~38% of BD total', trend: 'stable' },
            { metric: 'Medical Essentials organic growth (FY25)', value: '~4–5% FXN', trend: 'positive' },
            { metric: 'Hospital procedure volume index (US)', value: 'Recovering to 2019 baseline', trend: 'positive' },
        ],
        historicalContext: 'Medical Essentials was created through the BD-CareFusion merger (2015) and BD-Bard acquisition (2017), consolidating medication management and infection prevention into the largest BD segment.',
        predictiveInsight: 'Medical Essentials organic growth of 4–5% FXN through FY27 is achievable as hospital capital spending normalizes post-pandemic — Alaris pump volume and pharmacy automation are incremental upside drivers.',
        dataQuality: 'High',
        modelAccuracy: '88%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 3,
        title: 'Q2 FY26 Revenue $4.7B (+5.0% Organic)',
        kpi: '$4.7B',
        kpiLabel: 'Q2 FY26 total revenue (+5.0% organic FXN)',
        insight: 'BD Q2 FY26 revenue of $4.7B grew 5.0% organically (FXN) — driven by BioPharma Systems GLP-1 prefillable syringe volume (+28%) and Medical Essentials hospital channel recovery. FY26 full-year revenue guidance is ~$19.8–20.0B, implying ~5% organic growth for the full year.',
        trend: 'up',
        value: '+5.0% organic FXN',
        priority: 'high',
        icon: BarChart3,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#1c519c]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Revenue Performance',
        confidenceScore: 95,
        dataSource: 'BD Q2 FY26 Earnings Release + Segment Revenue Tables',
        lastUpdated: '1 hour ago',
        aiRecommendations: [
            'Bridge Q2 FY26 organic growth to FY26 guidance: sustaining 5% FXN for H2 requires Medical Essentials volume consistency and BioPharma Systems GLP-1 ramp',
            'Separate FX translation impact from organic growth in investor communications — FX is a presentation issue, not an operational one',
            'Track BD revenue by geography: China VoBP headwind vs EM growth differential is the key regional variance to monitor',
        ],
        impactedMetrics: [
            { metric: 'Q2 FY26 total revenue', value: '$4.7B (+5.0% organic)', trend: 'positive' },
            { metric: 'FY26 revenue guidance', value: '~$19.8–20.0B', trend: 'positive' },
            { metric: 'BioPharma Systems revenue contribution', value: '+28% GLP-1 growth driver', trend: 'positive' },
        ],
        historicalContext: 'BD revenue was $20.2B (FY2024) before BD Diagnostics segment spin-off, which closed mid-FY25. Post-spin BD revenue base is ~$19B, with organic growth of 4–6% FXN as the primary long-term value driver.',
        predictiveInsight: 'If GLP-1 device demand sustains +25%+ growth and Alaris placements ramp to plan, BD FY26 organic revenue could approach the high end of guidance — with FX translation the primary downside risk to reported growth.',
        dataQuality: 'Very High',
        modelAccuracy: '93%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 4,
        title: 'BioPharma Systems GLP-1: +28% Growth',
        kpi: '+28%',
        kpiLabel: 'BioPharma Systems GLP-1 Device Category Growth (Q2 FY26)',
        insight: 'BD BioPharma Systems GLP-1 prefillable syringe revenue grew +28% YoY in Q2 FY26 — driven by accelerating demand from GLP-1 drug manufacturers (Novo Nordisk, Eli Lilly, others) scaling global production. BD is a leading supplier of prefillable syringe systems and auto-injector components. Each $100M incremental BioPharma revenue ≈ +$0.06 Adj. EPS.',
        trend: 'up',
        value: '+$0.06 Adj. EPS per $100M',
        priority: 'high',
        icon: Target,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#1c519c]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'BioPharma Systems',
        confidenceScore: 94,
        dataSource: 'BD Q2 FY26 Earnings Call + BioPharma Systems Segment Data',
        lastUpdated: '30 minutes ago',
        aiRecommendations: [
            'Model GLP-1 demand scenarios through FY28: Novo + Lilly combined production scaling implies BioPharma Systems CAGR of 20–25%',
            'Track capacity expansion at BD BioPharma manufacturing sites — Holdrege (NE), Le Pont-de-Claix (France), and Fukushima (Japan) are key sites',
            'Monitor new GLP-1 entrants (AstraZeneca, Pfizer, Roche) — incremental manufacturer relationships expand BD\'s addressable market',
        ],
        impactedMetrics: [
            { metric: 'GLP-1 device category growth (Q2 FY26)', value: '+28% YoY', trend: 'positive' },
            { metric: 'BioPharma Systems as % of BD revenue', value: '~22%', trend: 'positive' },
            { metric: 'EPS sensitivity per $100M BioPharma revenue', value: '+$0.06 Adj. EPS', trend: 'positive' },
        ],
        historicalContext: 'BD BioPharma Systems has supplied prefillable syringes and drug delivery components to pharmaceutical manufacturers for 30+ years. The GLP-1 obesity/diabetes drug surge (2023–present) is the largest single demand acceleration in the segment\'s history.',
        predictiveInsight: 'GLP-1 drug sales are projected to exceed $100B globally by 2030 (Goldman Sachs estimates). BD\'s device component market share of ~30–35% positions it to capture $3–5B of cumulative incremental BioPharma revenue through FY30 — the most significant BD earnings growth driver outside BD Simplify.',
        dataQuality: 'Very High',
        modelAccuracy: '91%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 5,
        title: 'Alaris Infusion Pump Return: 80 Placements/Qtr',
        kpi: '80',
        kpiLabel: 'Alaris pump placements per quarter (Q2 FY26)',
        insight: 'BD Alaris infusion pump placements reached 80 per quarter in Q2 FY26 as consent decree remediation progresses ahead of schedule. Hospital procurement pipelines are rebuilding post-FDA resolution. FY27 target: 150–200 placements/quarter, representing $90–120M quarterly Connected Care uplift versus current run-rate.',
        trend: 'up',
        value: 'Target 150–200/qtr by FY27',
        priority: 'high',
        icon: BarChart3,
        bgColor: 'bg-blue-50',
        iconColor: 'text-[#1c519c]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Connected Care — Alaris',
        confidenceScore: 88,
        dataSource: 'BD Q2 FY26 Earnings Call + Connected Care Segment Update',
        lastUpdated: '15 minutes ago',
        aiRecommendations: [
            'Track hospital procurement cycle timing: 6–9 month lag from FDA consent decree lift to purchase orders means Q2 FY26 placements reflect decisions made in Q3/Q4 FY25',
            'Monitor Alaris vs. competitor pump placements (ICU Medical Plum, Baxter Sigma) — market share recapture pace is the key variable',
            'Quantify Alaris pull-through: each pump placement generates 10+ years of disposable and service revenue at 60%+ gross margin',
        ],
        impactedMetrics: [
            { metric: 'Alaris placements (Q2 FY26)', value: '80 units/quarter', trend: 'positive' },
            { metric: 'FY27 placement target', value: '150–200 units/quarter', trend: 'positive' },
            { metric: 'Connected Care revenue uplift at target', value: '$90–120M quarterly vs. current', trend: 'positive' },
        ],
        historicalContext: 'BD Alaris entered an FDA consent decree in 2020 following software and quality issues. The consent decree restricted BD from manufacturing and selling new Alaris pumps for ~3 years, resulting in significant market share loss to ICU Medical and Baxter.',
        predictiveInsight: 'Full Alaris consent decree resolution by Q4 FY26 and ramp to 150–200 placements/quarter by FY27 would add ~$400–500M annual Connected Care revenue run-rate vs. FY25 trough — representing +$0.15–0.20 Adj. EPS uplift.',
        dataQuality: 'High',
        modelAccuracy: '84%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 6,
        title: 'FX Translation Headwind: −$50M/Quarter',
        kpi: '−$50M',
        kpiLabel: 'Quarterly FX translation impact (Q2 FY26)',
        insight: '~50% of BD revenue is international, making FX translation a persistent earnings headwind when the USD strengthens. Q2 FY26 FX translation impact was −$50M vs. plan. BD\'s hedging program partially offsets transaction exposure but does not fully cover translation. Each $50M FX headwind ≈ −$0.03 Adj. EPS.',
        trend: 'down',
        value: '~50% international revenue',
        priority: 'medium',
        icon: Globe,
        bgColor: 'bg-amber-50',
        iconColor: 'text-amber-700',
        valueColor: 'text-red-600',
        action: 'View Details',
        category: 'FX & Currency Risk',
        confidenceScore: 91,
        dataSource: 'BD Q2 FY26 Earnings Release + FX Sensitivity Disclosures',
        lastUpdated: '3 hours ago',
        aiRecommendations: [
            'Bridge FX translation vs. organic growth in quarterly communications — reported growth can obscure strong underlying volume momentum',
            'Monitor EUR/USD, CNY/USD, JPY/USD rates — these three pairs drive ~70% of BD\'s FX translation exposure',
            'Assess natural hedge opportunities in international cost base — manufacturing footprint partially offsets revenue FX exposure',
        ],
        impactedMetrics: [
            { metric: 'FX translation impact (Q2 FY26)', value: '−$50M vs. plan', trend: 'negative' },
            { metric: 'International revenue share', value: '~50% of BD total', trend: 'stable' },
            { metric: 'EPS sensitivity per $50M FX headwind', value: '−$0.03 Adj. EPS', trend: 'negative' },
        ],
        historicalContext: 'BD FX headwinds have been a persistent earnings feature since the BD-Bard merger (2017) expanded international exposure. 2022–2023 USD strength created >$400M annual FX headwind; dollar moderation in 2024–2025 provided partial relief.',
        predictiveInsight: 'A 5% USD appreciation scenario vs. current rates would add ~$200M annual FX headwind — partially offset by BD\'s manufacturing cost base in Europe and Asia. FX remains the primary variance between organic and reported growth rates.',
        dataQuality: 'Very High',
        modelAccuracy: '90%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 7,
        title: 'Alaris Consent Decree: Q4 FY26 Resolution Target',
        kpi: 'Q4 FY26',
        kpiLabel: 'Estimated Alaris consent decree formal resolution',
        insight: 'BD Alaris consent decree formal resolution is targeted for Q4 FY26, though FDA inspection completion does not guarantee a specific lift timeline. Hospital procurement cycles add 6–9 months post-lift for new purchase orders. Each quarter of delay ≈ −40 placements and −$24M Connected Care revenue.',
        trend: 'flat',
        value: 'FDA inspection complete',
        priority: 'high',
        icon: Clock,
        bgColor: 'bg-amber-50',
        iconColor: 'text-amber-700',
        valueColor: 'text-amber-600',
        action: 'View Details',
        category: 'Alaris Execution Risk',
        confidenceScore: 80,
        dataSource: 'BD Q2 FY26 Earnings Call + FDA Consent Decree Status Update',
        lastUpdated: '1 hour ago',
        aiRecommendations: [
            'Track FDA 483 observations and warning letter status — any new quality findings could reset the consent decree resolution timeline',
            'Model quarterly delay scenarios: each quarter of Alaris delay ≈ −40 placements × ~$600K ASP = −$24M Connected Care revenue',
            'Monitor competitor pump installed base: ICU Medical and Baxter have gained accounts during BD Alaris suspension — recapture will require pricing concessions',
        ],
        impactedMetrics: [
            { metric: 'Consent decree resolution target', value: 'Q4 FY26 (indicative)', trend: 'stable' },
            { metric: 'Revenue per quarterly delay', value: '−$24M Connected Care revenue', trend: 'negative' },
            { metric: 'Capex committed for Alaris remediation', value: '~$120M', trend: 'stable' },
        ],
        historicalContext: 'The Alaris consent decree was entered in 2020 following FDA inspections that identified software and quality system deficiencies in BD\'s Medication Management Solutions unit. The decree halted new Alaris system sales and created a multi-year remediation program.',
        predictiveInsight: 'Post-consent decree lift, BD Alaris faces a 12–18 month ramp period before placements reach target run-rate. Full $400–500M annual revenue recovery is a FY28 event at the earliest — but pull-through disposable revenue makes each early placement highly valuable.',
        dataQuality: 'Medium',
        modelAccuracy: '78%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 8,
        title: 'BD Simplify: $120M Quarterly Run-Rate Savings',
        kpi: '$120M',
        kpiLabel: 'Q2 FY26 BD Simplify quarterly run-rate savings',
        insight: 'BD Simplify transformation program delivered $120M quarterly run-rate savings in Q2 FY26 — on track toward the $300M+ annual run-rate target by FY27. Manufacturing footprint optimization, procurement savings, and SG&A efficiency are primary drivers. BD Simplify savings directly expand Adj. operating margin.',
        trend: 'up',
        value: '$300M+ annual target by FY27',
        priority: 'high',
        icon: DollarSign,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#1c519c]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'BD Simplify Program',
        confidenceScore: 92,
        dataSource: 'BD Q2 FY26 Earnings Call + BD Simplify Program Update',
        lastUpdated: '10 minutes ago',
        aiRecommendations: [
            'Bridge $120M quarterly run-rate to $300M+ annual target — H2 FY26 and FY27 savings buckets must be identified and de-risked',
            'Quantify BD Simplify savings by category: manufacturing (60%), procurement (25%), SG&A (15%) — each has different execution risk',
            'Track one-time restructuring charges vs. recurring run-rate savings — Q2 FY26 includes charges that reduce GAAP earnings but do not affect Adj. EPS',
        ],
        impactedMetrics: [
            { metric: 'Q2 FY26 BD Simplify run-rate savings', value: '$120M quarterly', trend: 'positive' },
            { metric: 'FY27 annual run-rate target', value: '$300M+', trend: 'positive' },
            { metric: 'Adj. operating margin expansion target', value: '+100–150bps by FY27', trend: 'positive' },
        ],
        historicalContext: 'BD Simplify was announced in FY24 as a multi-year operational transformation program targeting $300M+ annual cost savings. The program followed the BD Diagnostics spin-off and reflects management\'s focus on margin expansion as the primary earnings growth lever beyond revenue.',
        predictiveInsight: 'Full $300M+ run-rate by FY27 would represent ~150–175bps of Adj. operating margin expansion at current revenue — adding ~$0.12–0.15 Adj. EPS on a run-rate basis. Manufacturing footprint consolidation is the highest-risk, highest-reward savings bucket.',
        dataQuality: 'High',
        modelAccuracy: '88%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 9,
        title: 'BD Diagnostics Spin-Off — Portfolio Simplification',
        kpi: 'FY25',
        kpiLabel: 'BD Diagnostics spin-off closed (FY25)',
        insight: 'The BD Diagnostics segment spin-off closed in FY25, creating a standalone diagnostics company and sharper focus for the remaining BD (Medical Essentials, Connected Care, BioPharma Systems, Interventional). Post-spin BD is a pure medtech company with higher margin profile and cleaner capital allocation story.',
        trend: 'up',
        value: 'Pure medtech focus post-spin',
        priority: 'medium',
        icon: Building2,
        bgColor: 'bg-blue-50',
        iconColor: 'text-[#1c519c]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Portfolio Strategy',
        confidenceScore: 96,
        dataSource: 'BD FY25 Annual Report + BD Diagnostics Spin-Off Disclosure',
        lastUpdated: '6 hours ago',
        aiRecommendations: [
            'Refresh BD investor narrative post-spin: four-segment medtech story is cleaner than the prior diversified healthcare model',
            'Track BD Diagnostics (SpinCo) performance vs. BD RemainCo — divergence validates or challenges the spin rationale',
            'Model BD capital allocation post-spin: higher FCF conversion and reduced debt creates M&A capacity in BioPharma and Interventional',
        ],
        impactedMetrics: [
            { metric: 'BD revenue base post-spin', value: '~$19B (vs. $20.2B pre-spin)', trend: 'stable' },
            { metric: 'Adj. operating margin post-spin', value: 'Higher than consolidated pre-spin', trend: 'positive' },
            { metric: 'BD Diagnostics (SpinCo) revenue', value: '~$1.2B annual', trend: 'stable' },
        ],
        historicalContext: 'BD acquired C.R. Bard in 2017 for $24B, creating one of the largest MedTech companies globally. The BD Diagnostics spin-off in FY25 was a strategic reversal — separating the lower-growth diagnostics business to focus on higher-growth medtech categories.',
        predictiveInsight: 'Post-spin BD\'s four core segments have stronger organic growth profiles than the divested diagnostics business — the portfolio simplification should drive multiple re-rating as investors value the cleaner medtech story at higher EV/EBITDA multiples.',
        dataQuality: 'Very High',
        modelAccuracy: '94%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 10,
        title: 'Interventional Organic Growth: +6.2% Q2 FY26',
        kpi: '+6.2%',
        kpiLabel: 'Interventional segment organic growth (Q2 FY26)',
        insight: 'BD Interventional segment achieved +6.2% organic growth in Q2 FY26, driven by vascular (peripheral intervention, electrophysiology) and surgical (hernia repair, biosurgery) market share gains. Interventional represents ~22% of BD revenue with a margin profile above the BD average — making it a key earnings quality contributor.',
        trend: 'up',
        value: '+6.2% organic Q2 FY26',
        priority: 'high',
        icon: Target,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#1c519c]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Interventional Segment',
        confidenceScore: 93,
        dataSource: 'BD Q2 FY26 Earnings Release + Interventional Segment Disclosures',
        lastUpdated: '45 minutes ago',
        aiRecommendations: [
            'Track vascular access and peripheral intervention market share vs. Medtronic, Boston Scientific, Abbott — Interventional growth is partly share gain, partly market expansion',
            'Quantify electrophysiology contribution: EP is the fastest-growing Interventional sub-segment and commands premium pricing',
            'Monitor surgical procedure volume trends: hernia repair and biosurgery are volume-driven and correlate with hospital ASC expansion',
        ],
        impactedMetrics: [
            { metric: 'Interventional organic growth (Q2 FY26)', value: '+6.2% FXN', trend: 'positive' },
            { metric: 'Interventional as % of BD revenue', value: '~22%', trend: 'positive' },
            { metric: 'Interventional Adj. margin vs. BD average', value: 'Above BD consolidated', trend: 'positive' },
        ],
        historicalContext: 'BD Interventional was created through the $24B C.R. Bard acquisition (2017), which brought peripheral vascular, surgical specialties, and urological products. BD Interventional has since expanded into electrophysiology and minimally invasive surgery.',
        predictiveInsight: 'Interventional organic growth of 6–8% FXN through FY27 is achievable as electrophysiology adoption expands and vascular access market grows. Each percentage point of Interventional organic growth contributes ~$40M revenue at current segment size.',
        dataQuality: 'High',
        modelAccuracy: '91%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 11,
        title: 'Free Cash Flow: $1.2B (Latest Quarter)',
        kpi: '$1.2B',
        kpiLabel: 'Free cash flow (latest reported quarter)',
        insight: 'BD free cash flow of ~$1.2B in the latest quarter reflects strong operating cash generation from Medical Essentials and BioPharma Systems. FY26 FCF guidance of ~$2.2–2.5B supports dividend growth and net leverage reduction to <2.5x by FY27. FCF conversion target is 85%+.',
        trend: 'up',
        value: 'FY26 guidance $2.2–2.5B',
        priority: 'high',
        icon: DollarSign,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#1c519c]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Cash Flow',
        confidenceScore: 91,
        dataSource: 'BD Q2 FY26 Cash Flow Statement + FY26 FCF Guidance',
        lastUpdated: '2 hours ago',
        aiRecommendations: [
            'Bridge quarterly FCF to FY26 guidance: $2.2–2.5B full-year implies $1.0–1.3B in H2 — achievable if BD Simplify cash costs normalize and working capital is managed',
            'Track FCF conversion: Adj. Net Income to FCF ratio — BD Simplify restructuring charges are a near-term FCF drag',
            'Monitor capex trends: BD capital spending of ~$600–700M/yr is well-controlled vs. medtech peers — maintaining FCF conversion above 85%',
        ],
        impactedMetrics: [
            { metric: 'FCF (latest quarter)', value: '~$1.2B', trend: 'positive' },
            { metric: 'FY26 FCF guidance', value: '$2.2–2.5B', trend: 'positive' },
            { metric: 'FCF conversion target', value: '85%+ (Adj. NI to FCF)', trend: 'positive' },
        ],
        historicalContext: 'BD FCF generation was constrained FY21–FY23 by Alaris consent decree remediation costs, BD-Bard integration expenses, and elevated capex. Post-spin FCF profile is cleaner, with BD Simplify savings providing structural FCF uplift through FY27.',
        predictiveInsight: 'Achieving $2.5B+ FCF by FY27 would give BD meaningful capital allocation flexibility: $800–900M annual dividend, $500M debt reduction, and $1B+ M&A capacity — enabling bolt-on acquisitions in BioPharma Systems or Interventional without rating agency pressure.',
        dataQuality: 'High',
        modelAccuracy: '89%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 12,
        title: 'FY26 Adj. EPS Guidance: ~$13.25–$13.50',
        kpi: '$13.25–$13.50',
        kpiLabel: 'FY2026 Adjusted EPS guidance',
        insight: 'BD FY26 Adjusted EPS guidance of ~$13.25–$13.50 is underpinned by 5% organic revenue growth, BD Simplify savings ($300M+ run-rate by FY27), and Alaris ramp. The 8–10% Adj. EPS CAGR target through FY27 reflects management\'s confidence in the three-driver model: revenue growth + margin expansion + leverage.',
        trend: 'up',
        value: '8–10% Adj. EPS CAGR target',
        priority: 'high',
        icon: Scale,
        bgColor: 'bg-blue-50',
        iconColor: 'text-[#1c519c]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Earnings Guidance',
        confidenceScore: 90,
        dataSource: 'BD Q2 FY26 Earnings Call + FY26 EPS Guidance Update',
        lastUpdated: '1 hour ago',
        aiRecommendations: [
            'Stress-test FY26 EPS at bear case: China VoBP $220M + Alaris delay 2 quarters + FX −$100M = ~$12.80 floor',
            'Model upside scenario: GLP-1 volume +$150M + BD Simplify ahead of plan + Alaris on-schedule = ~$13.65',
            'Align 8–10% CAGR narrative with FY27 consensus: $13.35 FY26 midpoint × 1.09 = ~$14.55 FY27E',
        ],
        impactedMetrics: [
            { metric: 'FY26 Adj. EPS guidance', value: '~$13.25–$13.50', trend: 'positive' },
            { metric: 'Long-term Adj. EPS CAGR target', value: '8–10% through FY27', trend: 'positive' },
            { metric: 'Q2 FY26 Adj. EPS (beat vs. consensus)', value: 'Beat by ~$0.05–0.10', trend: 'positive' },
        ],
        historicalContext: 'BD Adj. EPS has grown from ~$10.50 (FY2020) through BD-Bard integration dilution to the current ~$12.50 (FY2025A) level. The BD Simplify program and Alaris return are designed to accelerate EPS CAGR to 8–10% from a ~5–6% baseline.',
        predictiveInsight: 'Achieving $13.50 FY26 Adj. EPS and sustaining 8–10% CAGR through FY27 implies ~$14.70 FY27 — at 18x forward P/E (medtech sector average), this would support a BDX stock price of ~$265. The GLP-1 device volume and BD Simplify execution are the two swing factors.',
        dataQuality: 'High',
        modelAccuracy: '90%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 13,
        title: 'BD Dividend: Growing Consistently',
        kpi: '$4.00',
        kpiLabel: 'Annual dividend per share (indicative)',
        insight: 'BD has grown its annual dividend consistently, with an indicated annual dividend of ~$4.00/share. BD\'s dividend payout ratio is sustainable at ~30% of Adj. EPS, leaving ample FCF for debt reduction and strategic M&A. BD is a Dividend Aristocrat with 50+ consecutive years of dividend increases.',
        trend: 'up',
        value: '50+ years of increases',
        priority: 'medium',
        icon: Landmark,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#1c519c]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Capital Returns',
        confidenceScore: 97,
        dataSource: 'BD Investor Relations — Dividend History',
        lastUpdated: '6 hours ago',
        aiRecommendations: [
            'Communicate dividend growth commitment: BD\'s Dividend Aristocrat status is a differentiating characteristic for income-oriented institutional investors',
            'Model dividend CAGR at 5–7%: sustainable given 30% payout ratio and 8–10% Adj. EPS CAGR target',
            'Track payout ratio vs. FCF conversion: maintaining <35% payout ratio ensures dividend safety even in adverse EPS scenarios',
        ],
        impactedMetrics: [
            { metric: 'Annual dividend per share', value: '~$4.00 (indicative)', trend: 'positive' },
            { metric: 'Dividend payout ratio', value: '~30% of Adj. EPS', trend: 'stable' },
            { metric: 'Consecutive dividend increases', value: '50+ years (Dividend Aristocrat)', trend: 'positive' },
        ],
        historicalContext: 'BD has paid and grown its dividend for over 50 consecutive years, earning S&P 500 Dividend Aristocrat status. The dividend was maintained throughout the BD-Bard integration, Alaris consent decree, and COVID-19 — demonstrating management\'s commitment to the capital return program.',
        predictiveInsight: 'At 5–7% dividend CAGR, BD\'s annual dividend reaches ~$4.50–4.60/share by FY28. Dividend yield compression risk (as stock price appreciates) is the primary risk to dividend attractiveness for income investors.',
        dataQuality: 'Very High',
        modelAccuracy: '96%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 14,
        title: 'Net Leverage: ~2.5x Net Debt/EBITDA',
        kpi: '~2.5x',
        kpiLabel: 'Net Debt / EBITDA (Q2 FY26)',
        insight: 'BD net leverage is ~2.5x Net Debt/EBITDA following the BD Diagnostics spin-off. Management targets <2.5x leverage by FY27 as FCF generation improves and BD Simplify savings flow through. Annual FCF guidance of ~$2.2–$2.5B is the primary deleveraging mechanism. Investment-grade ratings maintained at all three agencies.',
        trend: 'down',
        value: 'Target <2.5x by FY27',
        priority: 'high',
        icon: Scale,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#1c519c]',
        valueColor: 'text-amber-600',
        action: 'View Details',
        category: 'Balance Sheet & Leverage',
        confidenceScore: 92,
        dataSource: 'BD Q2 FY26 Balance Sheet + Rating Agency Framework',
        lastUpdated: '6 hours ago',
        aiRecommendations: [
            'Monitor FFO/Debt and Net Debt/EBITDA quarterly — rating agencies (Moody\'s Baa1, S&P BBB+) use these metrics to assess BD\'s investment-grade headroom',
            'Track debt maturity schedule: LTD ~$17B with staggered maturities — refinancing risk is manageable at current credit spread levels',
            'Model leverage trajectory: at $2.4B FCF and $800M dividend, BD can reduce net debt ~$1.6B/yr — reaching <2.5x by mid-FY27',
        ],
        impactedMetrics: [
            { metric: 'Net Debt / EBITDA (Q2 FY26)', value: '~2.5x', trend: 'positive' },
            { metric: 'Long-term debt balance', value: '~$17B', trend: 'stable' },
            { metric: 'FY27 leverage target', value: '<2.5x Net Debt/EBITDA', trend: 'positive' },
        ],
        historicalContext: 'BD net leverage peaked at ~4.0x following the $24B C.R. Bard acquisition (2017). Systematic deleveraging through FCF generation brought leverage to ~2.8x by FY23. The BD Diagnostics spin-off (FY25) further reduced the debt base relative to EBITDA.',
        predictiveInsight: 'Reaching <2.5x leverage by FY27 would restore BD\'s pre-Bard acquisition balance sheet flexibility — enabling $2–3B of M&A capacity without rating agency pressure. BioPharma Systems capacity expansion and Interventional bolt-on acquisitions are the most likely deployment areas.',
        dataQuality: 'High',
        modelAccuracy: '91%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 15,
        title: 'Adj. Operating Income ~$1.1B (Q2 FY26)',
        kpi: '~$1.1B',
        kpiLabel: 'Adj. operating income (Q2 FY26)',
        insight: 'BD Adjusted Operating Income of ~$1.1B in Q2 FY26 reflects 5% organic revenue growth plus BD Simplify savings ($120M quarterly run-rate). Adj. operating margin expansion is on track toward the FY26 guidance target. FY26 full-year Adj. EPS guidance of ~$13.25–$13.50 implies ~8% growth vs. FY25A, anchored by margin expansion and revenue growth.',
        trend: 'up',
        value: 'FY26 Adj. EPS ~$13.25–$13.50',
        priority: 'high',
        icon: BarChart3,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#1c519c]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Earnings & Profitability',
        confidenceScore: 93,
        dataSource: 'BD Q2 FY26 Earnings Release + Income Statement',
        lastUpdated: '1 hour ago',
        aiRecommendations: [
            'Bridge Adj. Operating Income to Adj. EPS: ~$1.1B quarterly operating income → ~$3.35 Adj. EPS/quarter after interest, tax, and share count',
            'Separate organic vs. BD Simplify contributions: revenue growth (~60% of earnings uplift) vs. margin expansion (~40%) — critical for investor confidence in sustainability',
            'Track Adj. operating margin vs. medtech peers (Medtronic, Becton peers): BD margin expansion trajectory supports a premium multiple',
        ],
        impactedMetrics: [
            { metric: 'Adj. operating income (Q2 FY26)', value: '~$1.1B', trend: 'positive' },
            { metric: 'FY26 Adj. EPS guidance', value: '~$13.25–$13.50', trend: 'positive' },
            { metric: 'BD Simplify contribution to margin', value: '$120M quarterly run-rate', trend: 'positive' },
        ],
        historicalContext: 'BD Adj. operating margin compressed during the BD-Bard integration (2017–2021) from ~22% to ~19% as integration costs, Alaris issues, and pandemic disruption weighed on profitability. BD Simplify is designed to restore and exceed the pre-Bard margin profile.',
        predictiveInsight: 'If BD Simplify delivers $300M+ annual savings by FY27 and organic revenue grows 5%, Adj. operating margin could reach 23–24% by FY27 — at par with medtech sector leaders. This would support Adj. EPS of ~$14.50–15.00 by FY27 at the high end of the guidance range.',
        dataQuality: 'Very High',
        modelAccuracy: '92%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
];
