import {
    BarChart3,
    Calendar,
    Clock,
    Building2,
    DollarSign,
    Globe,
    Landmark,
    PieChart,
    Scale,
    Target,
    Users,
} from 'lucide-react';

import type { PersonalizedInsight } from './search-types';

// ── Personalized Insights (Delta Finance360 / CFO scoreboard aligned) ─────────
// IDs are stable — HomeTileSection + CFOTiles reference these for modal detail.

export const personalizedInsights: PersonalizedInsight[] = [
    {
        id: 1,
        title: 'ESA Contracted Load: 2.2 GW',
        kpi: '2.2 GW',
        kpiLabel: 'Binding ESA load (Feb 2026)',
        insight: 'BD secured 2.2 GW of binding Energy Service Agreements in Missouri as of February 2026, driven by hyperscaler AI data center investment — providing multi-year rate base and revenue visibility at 12.08¢/kWh, 29% below US average.',
        trend: 'up',
        value: '+$0.08 EPS/GW',
        priority: 'high',
        icon: Globe,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#003B2C]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Missouri Performance',
        confidenceScore: 95,
        dataSource: 'Q1 2026 10-Q + Earnings Call (May 2026)',
        lastUpdated: '2 hours ago',
        aiRecommendations: [
            'Monitor ESA pipeline execution: 3.4 GW total MO pipeline + 850 MW IL pipeline — each 1 GW binding adds ~$0.08 EPS',
            'Track Missouri kWh sales CAGR vs 6.2% guidance — data center ramp is primary upside driver',
            'Quantify rate base CWIP classification for ESA-driven transmission and distribution upgrades',
        ],
        impactedMetrics: [
            { metric: 'ESA Binding Load (Feb 2026)', value: '2.2 GW', trend: 'positive' },
            { metric: 'Missouri kWh Sales CAGR (FY26 guidance)', value: '6.2%', trend: 'positive' },
            { metric: 'EPS sensitivity per GW ESA', value: '+$0.08 EPS', trend: 'positive' },
        ],
        historicalContext: 'Missouri ESA pipeline grew from minimal data center activity (FY2023) to 2.2 GW binding (Feb 2026), reflecting BD\'s competitive 12.08¢/kWh rate — 29% below national average.',
        predictiveInsight: 'If 3.4 GW MO + 850 MW IL pipeline converts at 70%, annualized ESA EPS uplift could approach $0.35–$0.40 vs FY26 baseline — a transformative earnings driver through 2029.',
        dataQuality: 'Very High',
        modelAccuracy: '94%',
        consoleLink: '/business-consoles/missouri-electric-operations',
        consoleAvailable: true,
    },
    {
        id: 2,
        title: 'Missouri Rate Base CAGR 13.6%',
        kpi: '13.6%',
        kpiLabel: 'Missouri rate base CAGR (FY25–30 plan)',
        insight: 'BD Care Benefits rate base is growing at 13.6% CAGR through 2030, anchored by $21.3B of the $31.8B five-year capital plan — the highest rate base growth rate among large regulated utilities in the Midwest.',
        trend: 'up',
        value: '$21.3B MO capex plan',
        priority: 'high',
        icon: Target,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#003B2C]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Missouri Performance',
        confidenceScore: 92,
        dataSource: 'Q1 2026 Investor Presentation + 5-Year Capital Plan',
        lastUpdated: '4 hours ago',
        aiRecommendations: [
            'Confirm PISA 85% deferral mechanism maintains rate base recognition pace — CWIP qualifying capital is the critical lever',
            'Monitor Missouri rate case timing: incremental rate case every 2–3 years to recover capex pace above PISA cap',
            'Track rate base CAGR vs peer utility benchmarks: 13.6% materially above sector average ~8%',
        ],
        impactedMetrics: [
            { metric: 'Missouri rate base (FY25A)', value: '~$15.8B', trend: 'positive' },
            { metric: 'Missouri rate base CAGR (FY25-30)', value: '13.6%', trend: 'positive' },
            { metric: 'PISA deferral rate', value: '85%', trend: 'positive' },
        ],
        historicalContext: 'Missouri rate base has grown from ~$10B (FY2020) to ~$15.8B (FY2025) — the ESA data center load and MYRP regulatory framework are accelerating the trajectory further.',
        predictiveInsight: 'At 13.6% CAGR, Missouri rate base reaches ~$30B by FY2030, implying ~$500M+ annual incremental allowed revenue — the foundation for sustained 6–8% EPS CAGR.',
        dataQuality: 'High',
        modelAccuracy: '89%',
        consoleLink: '/business-consoles/capital-program-rate-base',
        consoleAvailable: true,
    },
    {
        id: 3,
        title: 'Q1 FY26 EPS $1.28 (+19.6% YoY)',
        kpi: '$1.28',
        kpiLabel: 'Diluted EPS (Q1 FY26, +19.6% YoY)',
        insight: '+19.6% YoY EPS growth in Q1 2026 — driven by Missouri PISA deferral benefit, ATXI formula rate outperformance, and Missouri ESA load beat — well above 6–8% CAGR long-term guidance midpoint.',
        trend: 'up',
        value: '+19.6% YoY',
        priority: 'medium',
        icon: DollarSign,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#003B2C]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Financial Performance',
        confidenceScore: 97,
        dataSource: 'Q1 2026 10-Q Statements of Operations',
        lastUpdated: '1 hour ago',
        aiRecommendations: [
            'Bridge Q1 EPS beat to FY26 guidance ($5.25–$5.45) — implies ~$4.07 in remaining quarters vs ~$4.14 in Q2-Q4 FY25',
            'Separate PISA timing benefit from structural rate base growth in EPS attribution for investor communications',
            'Highlight EPS sensitivity: +1% Missouri kWh CAGR ≈ +$0.04 EPS; +1 GW ESA ≈ +$0.08 EPS',
        ],
        impactedMetrics: [
            { metric: 'Diluted EPS (Q1 FY26)', value: '$1.28 (+19.6% YoY)', trend: 'positive' },
            { metric: 'Operating Income (Q1 FY26)', value: '$532M (+$254M YoY)', trend: 'positive' },
            { metric: 'Net Income (Q1 FY26)', value: '$357M', trend: 'positive' },
        ],
        historicalContext: 'AEE EPS has grown from ~$3.65 (FY2020) to $5.35 guidance (FY2026E), reflecting regulated rate base growth, PISA mechanism, and favorable Missouri regulatory environment.',
        predictiveInsight: 'Q1 FY26 beat positions BD well for the high end of $5.25–$5.45 guidance — FY26 EPS momentum depends on Missouri kWh sales trajectory and capex execution in Q2-Q4.',
        dataQuality: 'Very High',
        modelAccuracy: '97%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 4,
        title: '$31.8B Five-Year Capital Plan',
        kpi: '$31.8B',
        kpiLabel: '5-year capex plan (2026–2030)',
        insight: 'BD\'s $31.8B five-year capital plan ($6.36B/yr average) is the largest in company history — Missouri $21.3B (67%), IED $5.6B (18%), CVS Pharmacy $2.8B (9%), ATXI $2.1B (6%) — funding rate base from $28.8B to $47.7B by 2030.',
        trend: 'up',
        value: '$6.36B/yr avg',
        priority: 'high',
        icon: Users,
        bgColor: 'bg-indigo-50',
        iconColor: 'text-indigo-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Capital Program',
        confidenceScore: 88,
        dataSource: 'Q1 2026 Investor Presentation + 5-Year Capital Plan',
        lastUpdated: '30 minutes ago',
        aiRecommendations: [
            'Track Q1 FY26 capex execution: $1,563M actual vs $1,055M prior year — +48% YoY capex ramp critical to rate base CAGR',
            'Monitor Missouri PSC review of MYRP and PISA framework — regulatory support is the capex execution risk',
            'Confirm supply chain and workforce capacity to execute $6.36B/yr — labor and materials availability is a key constraint',
        ],
        impactedMetrics: [
            { metric: '5-year capex plan', value: '$31.8B ($6.36B/yr avg)', trend: 'positive' },
            { metric: 'Q1 FY26 capex actual', value: '$1,563M (+48% YoY)', trend: 'positive' },
            { metric: 'Rate base (FY30T)', value: '$47.7B', trend: 'positive' },
        ],
        historicalContext: 'BD capex has escalated from ~$2.5B/yr (FY2020) to $5.3B (FY25A) to $6.36B (FY26E) — driven by ESA data center load, Missouri grid modernization, and MISO LRTP transmission investment.',
        predictiveInsight: 'Each $100M of additional capex translates to +$0.01–0.02 EPS over a 3–5 year horizon as CWIP converts to rate base and earns allowed return — the $31.8B plan is the structural EPS CAGR engine.',
        dataQuality: 'High',
        modelAccuracy: '88%',
        consoleLink: '/business-consoles/capital-program-rate-base',
        consoleAvailable: true,
    },
    {
        id: 5,
        title: 'BD Services Earned ROE Gap',
        kpi: '8.72%',
        kpiLabel: 'BD Services earned ROE vs 9.22% allowed (−50bps gap)',
        insight: 'BD Services earned ROE of 8.72% vs 9.22% allowed — a 50bps underperformance on ~$5.0B Illinois rate base representing ~$25M annual earnings gap. Illinois formula rate adjustments and O&M discipline are the primary recovery levers.',
        trend: 'up',
        value: '−50bps gap to close',
        priority: 'medium',
        icon: Building2,
        bgColor: 'bg-teal-50',
        iconColor: 'text-teal-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'IED Performance',
        confidenceScore: 93,
        dataSource: 'Q1 2026 Segment P&L + Illinois ICC Formula Rate',
        lastUpdated: '15 minutes ago',
        aiRecommendations: [
            'Accelerate BD Services formula rate true-up — close gap to 9.22% allowed ROE via net plant additions and O&M discipline',
            'Monitor Illinois ICC annual formula rate reconciliation — FY26 rate year determines timing of ROE gap recovery',
            'Benchmark IED earned ROE vs comparable Illinois utilities (ComEd, Nicor) to assess structural vs cyclical gap',
        ],
        impactedMetrics: [
            { metric: 'IED earned ROE (FY25)', value: '8.72%', trend: 'positive' },
            { metric: 'IED allowed ROE (ICC formula)', value: '9.22%', trend: 'stable' },
            { metric: 'IED rate base (FY25A)', value: '~$5.0B', trend: 'positive' },
        ],
        historicalContext: 'BD Services ROE gap reflects elevated O&M and the lag between capital investment and formula rate recovery — Illinois PPRA and MYRP mechanisms help but don\'t eliminate the gap entirely.',
        predictiveInsight: 'Closing the 50bps IED ROE gap fully by FY27 would add ~$25M NI annually — each 100bps improvement = +$25M at $5.0B rate base × 50% equity ratio.',
        dataQuality: 'High',
        modelAccuracy: '92%',
        consoleLink: '/business-consoles/illinois-electric-distribution',
        consoleAvailable: true,
    },
    {
        id: 6,
        title: 'Missouri Revenue Mix: 44% of Total',
        kpi: '44%',
        kpiLabel: 'Missouri % of AEE total revenue (FY26E)',
        insight: 'BD Care Benefits represents ~44% of consolidated revenue with the highest rate base growth rate (13.6% CAGR) — ESA data center load is accelerating Missouri\'s revenue share further as IED and CVS Pharmacy grow more modestly.',
        trend: 'up',
        value: '+rate base 67% of plan',
        priority: 'medium',
        icon: Globe,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-emerald-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Revenue Mix',
        confidenceScore: 94,
        dataSource: 'Segment revenue disclosures (Q1 2026 10-Q)',
        lastUpdated: '3 hours ago',
        aiRecommendations: [
            'Highlight Missouri concentration risk to investors — if Missouri rate case is delayed, ~44% of revenue is at risk of regulatory lag',
            'Model blended allowed ROE improvement from Missouri mix shift: Missouri higher-rate-base growth drives consolidated EPS CAGR',
            'Refresh segment mix post-FY26 with ESA data center load fully ramped into Missouri revenue share',
        ],
        impactedMetrics: [
            { metric: 'Missouri revenue share (FY26E)', value: '~44%', trend: 'positive' },
            { metric: 'Missouri rate base CAGR (FY25-30)', value: '13.6%', trend: 'positive' },
            { metric: 'Missouri 5-yr capex share', value: '67% of $31.8B', trend: 'positive' },
        ],
        historicalContext: 'Missouri has grown from ~40% of consolidated revenue (FY2020) toward 44%+ (FY2026E) as the ESA pipeline and rate base growth outpace IED and CVS Pharmacy growth rates.',
        predictiveInsight: 'Post-2028 with ESA fully ramped, Missouri could represent 48–50% of consolidated revenue — making Missouri regulatory outcomes the dominant driver of consolidated EPS variability.',
        dataQuality: 'Very High',
        modelAccuracy: '95%',
        consoleLink: '/business-consoles/missouri-electric-operations',
        consoleAvailable: true,
    },
    {
        id: 7,
        title: 'ATXI FERC Transmission: 10.48% ROE',
        kpi: '10.48%',
        kpiLabel: 'ATXI allowed ROE (FERC formula; ~$3.2B rate base)',
        insight: 'ATXI earns 10.48% allowed ROE on ~$3.2B FERC formula rate base — the highest allowed return in the BD portfolio. MISO LRTP portfolio (~$2.2B) expands the ATXI rate base and earnings contribution through 2030.',
        trend: 'up',
        value: '$2.2B MISO LRTP',
        priority: 'high',
        icon: DollarSign,
        bgColor: 'bg-amber-50',
        iconColor: 'text-amber-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Transmission',
        confidenceScore: 93,
        dataSource: 'Q1 2026 Segment P&L + FERC Formula Rate Filing',
        lastUpdated: '1 hour ago',
        aiRecommendations: [
            'Track MISO LRTP project awards and in-service dates — each project in-service immediately earns 10.48% FERC formula ROE',
            'Monitor FERC ROE proceeding risk: industry-wide challenges to base ROE adders could affect ATXI\'s 10.48% allowed return',
            'Quantify Q1 FY26 ATXI outperformance ($15M above plan) as evidence of accelerated LRTP execution',
        ],
        impactedMetrics: [
            { metric: 'ATXI allowed ROE (FERC formula)', value: '10.48%', trend: 'stable' },
            { metric: 'ATXI rate base (FY25A)', value: '~$3.2B', trend: 'positive' },
            { metric: 'MISO LRTP portfolio', value: '~$2.2B', trend: 'positive' },
        ],
        historicalContext: 'ATXI rate base has grown from ~$1.5B (FY2018) to ~$3.2B (FY2025) via MISO transmission expansion — LRTP projects awarded FY2023-2025 will drive further rate base growth through 2030.',
        predictiveInsight: 'Full MISO LRTP construction could push ATXI rate base to ~$5.0B by FY2030 — adding ~$180M in annual FERC formula revenue at 10.48% ROE, making ATXI an increasingly material AEE earnings driver.',
        dataQuality: 'Very High',
        modelAccuracy: '94%',
        consoleLink: '/business-consoles/transmission-infrastructure',
        consoleAvailable: true,
    },
    {
        id: 8,
        title: 'IRA Tax Credit Benefits: $1.8B (2026–30)',
        kpi: '$1.8B',
        kpiLabel: 'IRA credits (2026–2030 plan)',
        insight: 'BD projects $1.8B in Inflation Reduction Act tax credits over 2026–2030 from clean energy additions — production tax credits (PTCs) from wind/solar and investment tax credits (ITCs) from Castle Bluff solar and storage.',
        trend: 'up',
        value: '~$360M/yr average',
        priority: 'high',
        icon: Landmark,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#003B2C]',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Clean Energy & IRA',
        confidenceScore: 96,
        dataSource: 'Q1 2026 Investor Presentation + IRA Credit Schedule',
        lastUpdated: '10 minutes ago',
        aiRecommendations: [
            'Quantify IRA credit flow-through to EPS: $360M/yr average at 21% effective tax rate = ~$0.18–0.20 annual EPS benefit',
            'Track clean energy additions vs 4,300 MW target — each 100 MW wind/solar ≈ $15–20M annual PTC',
            'Monitor IRA regulatory guidance updates (safe harbor rules, transferability) for credit monetization strategies',
        ],
        impactedMetrics: [
            { metric: 'Total IRA credits (2026–2030)', value: '$1.8B', trend: 'positive' },
            { metric: 'Clean energy additions target', value: '4,300 MW', trend: 'positive' },
            { metric: 'Avg annual IRA benefit', value: '~$360M', trend: 'positive' },
        ],
        historicalContext: 'The Inflation Reduction Act (2022) created a 10-year PTC/ITC window that transforms BD\'s clean energy investment economics — making wind and solar cost-competitive vs. fossil generation.',
        predictiveInsight: 'IRA credit monetization via transferability provisions could allow BD to accelerate credit value capture in near-term — reducing effective financing cost of clean energy capex by 15–20%.',
        dataQuality: 'High',
        modelAccuracy: '93%',
        consoleLink: '/business-consoles/clean-energy-transition',
        consoleAvailable: true,
    },
    {
        id: 9,
        title: 'Missouri SAIFI Grid Reliability',
        kpi: '1.18',
        kpiLabel: 'Missouri SAIFI (FY25A; customer interruptions/yr)',
        insight: 'Missouri SAIFI of 1.18 interruptions per customer per year reflects ongoing grid modernization investment — BD\'s $31.8B capital plan includes significant distribution automation and hardening investment targeting top-quartile reliability.',
        trend: 'up',
        value: 'Top-quartile target',
        priority: 'medium',
        icon: Users,
        bgColor: 'bg-green-50',
        iconColor: 'text-green-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Customer & Operations',
        confidenceScore: 87,
        dataSource: 'BD Care Benefits Annual Operations Report + MPSC Filing',
        lastUpdated: '45 minutes ago',
        aiRecommendations: [
            'Link grid reliability performance to Missouri MYRP metrics — SAIFI improvement supports regulatory approval of accelerated capex',
            'Quantify customer satisfaction (J.D. Power) correlation to reliability for MPSC rate case support',
            'Track Missouri smart meter penetration rate — AMI deployment is a key driver of SAIFI improvement',
        ],
        impactedMetrics: [
            { metric: 'Missouri SAIFI (FY25A)', value: '1.18 interruptions/yr', trend: 'positive' },
            { metric: 'AMI meter deployment', value: '>1.2M deployed', trend: 'positive' },
            { metric: 'Distribution automation investment', value: 'Included in MO $21.3B plan', trend: 'positive' },
        ],
        historicalContext: 'Missouri SAIFI has improved from ~1.45 (FY2018) to 1.18 (FY25A) as grid hardening and automation investment accelerated — further improvement supports MYRP performance scorecard.',
        predictiveInsight: 'Top-quartile SAIFI (<1.05) by FY2030 is achievable if Missouri grid modernization executes on plan — directly supports continued MYRP regulatory framework approval and rate case outcomes.',
        dataQuality: 'Medium',
        modelAccuracy: '85%',
        consoleLink: '/business-consoles/grid-modernization',
        consoleAvailable: true,
    },
    {
        id: 10,
        title: 'FFO/Debt Ratio: 16.2%',
        kpi: '16.2%',
        kpiLabel: 'FFO/Debt (Q1 FY26; target 16-17%)',
        insight: 'BD FFO/debt of 16.2% is within the 16–17% target range — the credit metric that anchors investment-grade ratings (Baa1/BBB+). The $31.8B capex plan and ~$4.5B equity ATM program maintain this ratio through 2030.',
        trend: 'up',
        value: '16–17% target',
        priority: 'high',
        icon: BarChart3,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-[#003B2C]',
        valueColor: 'text-amber-600',
        action: 'View Details',
        category: 'Credit Metrics',
        confidenceScore: 90,
        dataSource: 'Q1 2026 Credit Metrics + Moody\'s/S&P Rating Agency Framework',
        lastUpdated: '6 hours ago',
        aiRecommendations: [
            'Monitor FFO/debt trajectory as capex ramps to $6.36B/yr — equity issuance pacing is critical to maintaining 16–17% target',
            'Stress-test FFO/debt at $0 rate case revenue increase — regulatory lag risk to credit metric',
            'Track ATM equity program: ~6.4M shares/yr keeps dilution manageable while supporting FFO/debt above 16%',
        ],
        impactedMetrics: [
            { metric: 'FFO/Debt (Q1 FY26)', value: '16.2%', trend: 'positive' },
            { metric: 'Long-term debt balance', value: '~$19B at ~3.5% avg cost', trend: 'stable' },
            { metric: 'ATM equity program', value: '~$4.5B / 7-yr plan', trend: 'positive' },
        ],
        historicalContext: 'AEE maintained FFO/debt above 15% through COVID and rising rate environments — the regulated utility model provides stable cash flows that anchor the credit metric even in adverse scenarios.',
        predictiveInsight: 'FFO/debt remaining above 16% through 2030 requires consistent O&M discipline, timely rate case recoveries, and equity issuance pacing — the three levers management can control.',
        dataQuality: 'High',
        modelAccuracy: '90%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 11,
        title: 'Q1 FY26 Capex $1,563M (+48%)',
        kpi: '$1,563M',
        kpiLabel: 'Q1 FY26 capital expenditures (+48% YoY)',
        insight: 'Q1 2026 capex of $1,563M is up 48% YoY — annualizing to ~$6.25B, in line with $6.3B FY26 guidance. Front-loading reflects Missouri transmission and generation investment for ESA data center load serving.',
        trend: 'up',
        value: '+48% YoY',
        priority: 'high',
        icon: PieChart,
        bgColor: 'bg-orange-50',
        iconColor: 'text-orange-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Capital Program',
        confidenceScore: 91,
        dataSource: 'Q1 2026 Cash Flow Statement + Capital Plan Update',
        lastUpdated: '2 hours ago',
        aiRecommendations: [
            'Bridge Q1 capex $1,563M to FY26 plan $6.3B — Q2-Q4 implies $4.74B remaining at ~$1.58B/quarter',
            'Track Missouri generation vs transmission capex split for regulatory recovery path (PISA vs formula rate)',
            'Monitor supply chain execution: equipment lead times for transformers, conductors, and switchgear are critical constraints',
        ],
        impactedMetrics: [
            { metric: 'Q1 FY26 capex', value: '$1,563M (+48% YoY)', trend: 'positive' },
            { metric: 'FY26 capex guidance', value: '~$6.3B', trend: 'stable' },
            { metric: 'FY26 capex to rate base bridge', value: '$6.3B → +~$1.7B net rate base', trend: 'positive' },
        ],
        historicalContext: 'BD capex accelerated from ~$2.8B (FY2020) to $5.3B (FY2025A) to $6.3B (FY2026E) — reflecting the combination of ESA data center load, MYRP generation replacement, and MISO LRTP transmission.',
        predictiveInsight: 'Sustained $6B+ annual capex through 2030 is unprecedented for BD and creates execution risk — supply chain resilience and project management capacity will determine whether the $31.8B plan is achieved on schedule.',
        dataQuality: 'High',
        modelAccuracy: '89%',
        consoleLink: '/business-consoles/capital-program-rate-base',
        consoleAvailable: true,
    },
    {
        id: 12,
        title: 'EPS Guidance: $5.25–$5.45',
        kpi: '$5.25–$5.45',
        kpiLabel: 'FY2026 EPS guidance (6–8% CAGR through 2030)',
        insight: 'BD reaffirmed FY2026 EPS guidance of $5.25–$5.45 following Q1 FY26 beat ($1.28 EPS) — underpinned by Missouri rate base CAGR, ESA data center load ramp, and PISA regulatory mechanism.',
        trend: 'up',
        value: '6–8% CAGR through 2030',
        priority: 'high',
        icon: Scale,
        bgColor: 'bg-red-50',
        iconColor: 'text-red-700',
        valueColor: 'text-amber-600',
        action: 'View Details',
        category: 'Earnings Guidance',
        confidenceScore: 90,
        dataSource: 'Q1 2026 Earnings Call + FY2026 EPS Guidance Reaffirmation',
        lastUpdated: '1 hour ago',
        aiRecommendations: [
            'Stress-test FY26 guidance at bear case: Missouri rate case delay (−$0.10 EPS) + slower ESA ramp (−$0.08 EPS) = ~$5.07 floor',
            'Model upside scenario: +1 GW ESA acceleration + ATXI outperformance = ~$5.55 EPS above guidance',
            'Align 6–8% CAGR narrative with investor expectations: $5.35 FY26 × 1.07 = $5.72 FY27E midpoint',
        ],
        impactedMetrics: [
            { metric: 'FY2026 EPS guidance', value: '$5.25–$5.45', trend: 'positive' },
            { metric: 'Q1 FY26 EPS actual', value: '$1.28 (+19.6% YoY)', trend: 'positive' },
            { metric: 'Long-term EPS CAGR target', value: '6–8% through 2030', trend: 'stable' },
        ],
        historicalContext: 'BD has consistently achieved or exceeded annual EPS guidance over 5 consecutive years — the PISA and formula rate mechanisms reduce regulatory lag and provide earnings consistency.',
        predictiveInsight: 'Achieving the high end of $5.45 requires full ESA ramp, successful Missouri rate case, and clean capex execution — each lever can swing EPS ±$0.08–0.15 individually.',
        dataQuality: 'High',
        modelAccuracy: '89%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
    {
        id: 13,
        title: 'Castle Bluff Solar + 4,300 MW Clean Energy',
        kpi: '4,300 MW',
        kpiLabel: 'Clean energy additions target (2026–2030)',
        insight: 'BD targets 4,300 MW of clean energy additions through 2030, anchored by Castle Bluff Solar and Wind (~1,200 MW) — replacing Labadie and Rush Island coal generation while satisfying data center ESA load with clean energy.',
        trend: 'up',
        value: 'Castle Bluff + wind',
        priority: 'medium',
        icon: BarChart3,
        bgColor: 'bg-green-50',
        iconColor: 'text-green-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Clean Energy & IRA',
        confidenceScore: 94,
        dataSource: 'Q1 2026 Earnings Call + Missouri MYRP Compliance Plan',
        lastUpdated: '4 hours ago',
        aiRecommendations: [
            'Confirm IRA PTC qualification for each wind/solar project — critical for $1.8B credit plan realization',
            'Track clean energy MW in-service dates vs MYRP compliance schedule — PSC approval milestones are the critical path',
            'Quantify ESA customer clean energy matching: hyperscalers require 24/7 clean energy — Missouri\'s renewable additions directly support ESA contract terms',
        ],
        impactedMetrics: [
            { metric: 'Clean energy additions target', value: '4,300 MW (2026–2030)', trend: 'positive' },
            { metric: 'Coal generation to retire', value: 'Labadie + Rush Island (~3,200 MW)', trend: 'positive' },
            { metric: 'IRA PTC benefit from wind/solar', value: 'Majority of $1.8B plan', trend: 'positive' },
        ],
        historicalContext: 'BD Care Benefits\'s MYRP (Integrated Resource Plan) filed 2023 charts a path from 60% coal (FY2020) to <20% coal by 2030 — ESA data center load growth has accelerated the clean energy build-out timeline.',
        predictiveInsight: '4,300 MW clean energy by 2030 positions Missouri for a 60% clean generation mix, directly supporting ESA contract requirements and Missouri\'s carbon reduction goals — a key regulatory goodwill investment.',
        dataQuality: 'Very High',
        modelAccuracy: '95%',
        consoleLink: '/business-consoles/clean-energy-transition',
        consoleAvailable: true,
    },
    {
        id: 14,
        title: 'Missouri Electric Rate: 12.08¢/kWh',
        kpi: '12.08¢/kWh',
        kpiLabel: 'Missouri electric rate (29% below US avg 17¢/kWh)',
        insight: 'BD Care Benefits\'s competitive 12.08¢/kWh electric rate — 29% below the US average of 17¢/kWh — is the primary driver of ESA data center demand. This rate advantage attracts hyperscaler investment that creates a virtuous cycle: more load → more capex → more rate base → more earnings.',
        trend: 'up',
        value: '29% below US avg',
        priority: 'medium',
        icon: Clock,
        bgColor: 'bg-emerald-50',
        iconColor: 'text-emerald-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Missouri Performance',
        confidenceScore: 96,
        dataSource: 'Missouri PSC Rate Filings + EIA State Electric Price Data',
        lastUpdated: '2 hours ago',
        aiRecommendations: [
            'Protect competitive rate advantage in Missouri rate cases — rate increases above CPI risk narrowing the 29% gap that attracts ESA customers',
            'Monitor Illinois rate comparison: BD Services rates are less competitive nationally — differentiate Missouri ESA attractiveness in investor messaging',
            'Track hyperscaler site selection criteria: rate competitiveness, clean energy, grid reliability, and transmission access',
        ],
        impactedMetrics: [
            { metric: 'Missouri electric rate', value: '12.08¢/kWh', trend: 'stable' },
            { metric: 'US avg residential electric rate', value: '~17¢/kWh', trend: 'negative' },
            { metric: 'Missouri rate advantage', value: '29% below US avg', trend: 'positive' },
        ],
        historicalContext: 'Missouri\'s low electric rates reflect abundant coal and nuclear generation (historically), proximity to Callaway Nuclear, and a constructive regulatory environment — the competitive position that enabled ESA data center attraction.',
        predictiveInsight: 'Maintaining a 20%+ rate advantage through 2030 is critical to ESA pipeline conversion — rate increases from the $31.8B capex plan must be balanced with load growth to protect Missouri\'s competitive electric price.',
        dataQuality: 'Very High',
        modelAccuracy: '96%',
        consoleLink: '/business-consoles/missouri-electric-operations',
        consoleAvailable: true,
    },
    {
        id: 15,
        title: '10-Yr Treasury Rate Sensitivity',
        kpi: '4.5%',
        kpiLabel: '10-yr Treasury (AEE financing cost proxy)',
        insight: 'BD carries ~$19B long-term debt at ~3.5% average cost — each +25bps in 10-yr Treasury rates increases annual interest expense by ~$8M as AEE refinances maturing debt. Weighted average debt maturity provides a multi-year buffer against rate rises.',
        trend: 'flat',
        value: '~$19B LTD at 3.5% avg',
        priority: 'high',
        icon: BarChart3,
        bgColor: 'bg-blue-50',
        iconColor: 'text-blue-700',
        valueColor: 'text-green-600',
        action: 'View Details',
        category: 'Leverage & Rates',
        confidenceScore: 89,
        dataSource: 'AEE 10-K FY2025 + Debt Schedule + EIA Interest Rate Forecasts',
        lastUpdated: '1 hour ago',
        aiRecommendations: [
            'Maintain AEE downside scenario at 6.0% 10-yr Treasury: higher refinancing cost could add $50M+ annual interest drag',
            'Bridge Treasury rate sensitivity to EPS: each +25bps ≈ −$0.01–0.02 EPS via new debt issuance over 2–3 years',
            'Pair Treasury rate risk with equity ATM execution — higher rates increase the cost of the $4.5B equity program vs debt financing',
        ],
        impactedMetrics: [
            { metric: '10-yr Treasury rate (current)', value: '~4.5%', trend: 'stable' },
            { metric: 'AEE long-term debt', value: '~$19B at ~3.5% avg cost', trend: 'stable' },
            { metric: 'Interest expense sensitivity', value: '~$8M / 25bps rise', trend: 'negative' },
        ],
        historicalContext: 'BD refinanced opportunistically at low rates (2020–2022) — average debt cost of 3.5% provides a meaningful below-market buffer. New debt issuances for the $31.8B capex plan will be at higher market rates.',
        predictiveInsight: 'A sustained 5.5%+ 10-yr Treasury would add ~$150M additional annual interest by FY2028 as ~$5B+ of existing debt matures and must be refinanced — the primary external earnings risk for a capital-intensive utility.',
        dataQuality: 'High',
        modelAccuracy: '88%',
        consoleLink: '/executive-summary',
        consoleAvailable: true,
    },
];
